Repository home-assistant/operating-system, pull requests merged in 2018-09, with the labels that each got.

#188 Do not assume index 0 for boot medium
  buildroot-external/bootloader/barebox/boot/system0
  buildroot-external/bootloader/barebox/boot/system1
Labels: REL-1, cla-signed

#196 MYLAN_SECRED_KEY should be MYLAN_SECRET_KEY, no?
  Documentation/network.md
Labels: cla-signed

#199 Update documentation for a static IPV4 address via nmcli
  Documentation/network.md
Labels: cla-signed, in progress
