Repository home-assistant/operating-system, pull requests merged in 2018-08, with the labels that each got.

#146 Fix some build errors
  Documentation/boards/raspberrypi.md
  Documentation/boards/tinker.md
  buildroot-external/board/tinker/patches/uboot/200-tinker-uart3-debug.patch
  buildroot-external/board/tinker/uboot-boot.sh
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.mk
  buildroot-external/package/bluetooth-rtl8723/bluetooth-rtl8723.mk
  buildroot-external/patches/uboot/0001-CMD-read-string-from-fileinto-env.patch
  buildroot-external/scripts/rauc.sh
  scripts/build-all.sh
Labels: cla-signed, in progress

#148 os: improve fileenv u-boot
  buildroot-external/patches/uboot/0001-CMD-read-string-from-fileinto-env.patch
Labels: cla-signed, in progress

#153 os: fix u-boot env size
  buildroot-external/board/raspberrypi/patches/uboot/0001-Support-HassOS-bootstate-partition.patch
  buildroot-external/board/raspberrypi/rpi/info
  buildroot-external/board/raspberrypi/rpi0-w/info
  buildroot-external/board/raspberrypi/rpi2/info
  buildroot-external/board/raspberrypi/rpi3-64/info
  buildroot-external/board/raspberrypi/rpi3/info
  buildroot-external/board/tinker/info
  buildroot-external/board/tinker/patches/uboot/0001-Support-HassOS-bootstate-partition.patch
  buildroot-external/board/tinker/uboot.config
  buildroot-external/bootloader/uboot.config
  buildroot-external/misc/fw_env.config
  buildroot-external/scripts/rauc.sh
Labels: cla-signed, in progress

#147 Documentation: Raspeberry Pi I2C
  Documentation/boards/raspberrypi.md
Labels: REL-1, cla-signed, in progress

#171 Fix syntax highlighting in network docs
  Documentation/network.md
Labels: cla-signed

#173 odroid-c2: Add device to auto build list
  scripts/build-all.sh
Labels: cla-signed, in progress

#174 raspberry: Use new config.txt
  buildroot-external/board/raspberrypi/boot-env.txt
  buildroot-external/board/raspberrypi/hassos-hook.sh
Labels: cla-signed, in progress

#175 Latest kernel updates/bugfixes
  Documentation/kernel.md
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-patches/0006-Pump-raspberry-pi-firmware-for-kernel-4.14.patch
  buildroot/package/rpi-firmware/rpi-firmware.hash
  buildroot/package/rpi-firmware/rpi-firmware.mk
Labels: cla-signed, in progress

#176 Odroid-C2: updating kernel to 4.14.67
  Documentation/kernel.md
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0001-ARM64-dts-meson-gxm-Add-support-for-Khadas-VIM2.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0004-phy-meson-add-USB3-PHY-support-for-Meson-GXL.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0005-usb-host-add-a-generic-platform-USB-roothub-driver.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0006-usb-host-xhci-plat-integrate-the-platform-roothub.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0007-ARM64-dts-meson-gxl-add-USB-host-support.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0008-ARM64-dts-meson-gxm-add-GXM-specific-USB-host-config.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0009-ARM64-dts-meson-gx-Enable-USB-on-GXL-and-GXM-boards.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0029-ARM64-dts-meson-gxl-add-sound-dai-cells-to-HDMI-node.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0030-ARM64-dts-meson-gxl-Take-eMMC-data-strobe-out-of-eMM.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0032-ARM64-dts-meson-gx-Add-HDMI_5V-regulator-on-selected.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0035-ARM64-dts-meson-activate-hdmi-audio-HDMI-enabled-boa.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0036-net-phy-meson-gxl-detect-LPA-corruption.patch
  buildroot-external/board/hardkernel/odroid-c2/patches/linux/0037-drm-meson-fix-vsync-buffer-update.patch
  buildroot-external/configs/odroid_c2_defconfig
Labels: cla-signed, in progress
