Repository home-assistant/operating-system, pull requests merged in 2018-10, with the labels that each got.

#208 Fixed typo in 'address' property name for Static IP
  Documentation/network.md
Labels: cla-signed

#209 Implement basic ACPI shutdown support via busybox acpid
  buildroot-external/rootfs-overlay/etc/acpi/PWRF/00000080
  buildroot-external/rootfs-overlay/etc/systemd/system/multi-user.target.wants/busybox-acpid.service
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/busybox-acpid.service
Labels: cla-signed

#210 Allow udev rules & make it persistent
  Documentation/configuration.md
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.mk
  buildroot-external/rootfs-overlay/etc/systemd/system/hassos-bind.target.wants/etc-udev-rules.d.mount
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/etc-udev-rules.d.mount
  buildroot-external/rootfs-overlay/usr/lib/udev/rules.d/hmip-rfusb.rules
  buildroot-external/rootfs-overlay/usr/sbin/hassos-config
  buildroot-external/scripts/rauc.sh
Labels: cla-signed, in progress

#216 Added 8021q kernel module for VLAN support
  buildroot-external/kernel/hassos-4_14.config
Labels: cla-signed

#217 OS: use newer docker run command
  buildroot-external/rootfs-overlay/usr/sbin/hassos-cli
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed, in progress

#220 Add informal "getting started with development" document
  Documentation/getting_started_development.md
Labels: cla-signed

#221 Enable XHCI (USB3) support in ova kernel config
  buildroot-external/board/ova/kernel.config
Labels: cla-signed

#222 Remove smart quotes and fix typo
  Documentation/network.md
Labels: cla-needed

#212 OS: Config importer support now also boot partition
  Documentation/configuration.md
  buildroot-external/rootfs-overlay/usr/sbin/hassos-config
Labels: cla-signed, in progress

#215 Uboot bootstate
  buildroot-external/board/asus/tinker/patches/uboot/0001-Support-HassOS-bootstate-partition.patch
  buildroot-external/board/asus/tinker/uboot-boot.sh
  buildroot-external/board/asus/tinker/uboot.config
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.sh
  buildroot-external/board/raspberrypi/patches/uboot/0001-Support-HassOS-bootstate-partition.patch
  buildroot-external/board/raspberrypi/rpi3-64/uboot-boot.sh
  buildroot-external/board/raspberrypi/uboot-boot.sh
  buildroot-external/board/raspberrypi/uboot.config
Labels: cla-signed, in progress

#228 Typo fix
  Documentation/boards/ova.md
Labels: cla-signed

#229 OS: bugfix acpid service file
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/busybox-acpid.service
Labels: cla-signed, in progress

#232 Fixed keeping name of udev rules after usb import
  buildroot-external/rootfs-overlay/usr/sbin/hassos-config
Labels: cla-signed

#235 Raspberry: Bugfix not try to load Bluetooth
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.service
Labels: cla-signed, in progress
