Repository home-assistant/operating-system, pull requests merged in 2018-07, with the labels that each got.

#60 Map /etc/machine-id into supervisor/cli
  buildroot-external/rootfs-overlay/usr/sbin/hassos-cli
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: REL-1, cla-signed, in progress

#61 Make logs persistent over reboot and cleanup
  buildroot-external/rootfs-overlay/etc/systemd/system/multi-user.target.wants/hassos-persists-journald.service
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/hassos-persists-journald.service
  buildroot-external/rootfs-overlay/usr/sbin/hassos-persists-journald
Labels: REL-1, cla-signed, in progress

#65 Fix spell in journald script
  buildroot-external/rootfs-overlay/usr/sbin/hassos-persists-journald
Labels: REL-1, cla-signed, in progress

#66 Fix label name in test script
  buildroot-external/rootfs-overlay/usr/sbin/hassos-config
Labels: REL-1, cla-signed, in progress

#67 Fix docker warning on rpi
  buildroot-external/board/raspberrypi/rpi3-64/uboot-boot.sh
  buildroot-external/board/raspberrypi/uboot-boot.sh
Labels: REL-1, cla-signed, in progress

#68 Fix update script with uptime
  buildroot-external/rootfs-overlay/usr/sbin/hassos-config
Labels: REL-1, cla-signed, in progress

#69 Change chmod of network connection files from fat32
  buildroot-external/rootfs-overlay/usr/sbin/hassos-config
Labels: REL-1, cla-signed, in progress

#70 Fix persistent log
  buildroot-external/rootfs-overlay/usr/sbin/hassos-config
  buildroot-external/rootfs-overlay/usr/sbin/hassos-persists-journald
Labels: REL-1, cla-signed, in progress

#71 Update CLI / Supervisor
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
Labels: REL-1, cla-signed, in progress

#51 Update network.md
  Documentation/network.md
Labels: cla-signed, in progress

#50 Update configuration.md
  Documentation/configuration.md
Labels: cla-signed, in progress

#78 Fix /usr/sbin/hassos-cli is not in /etc/shells
  buildroot-external/scripts/rootfs-layer.sh
Labels: REL-1, cla-signed, in progress

#80 Fix config documentation closing tags
  Documentation/configuration.md
Labels: REL-1, cla-signed

#75 Use dhcp client / avahi after NM
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/rootfs-overlay/etc/NetworkManager/NetworkManager.conf
  buildroot-external/rootfs-overlay/etc/systemd/system/avahi-daemon.service.d/nm.conf
  buildroot-external/rootfs-overlay/etc/systemd/system/hassos-bind.target.wants/var-lib-NetworkManager.mount
  buildroot-external/rootfs-overlay/etc/tmpfiles.d/nm.conf
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/etc-NetworkManager-system\x2dconnections.mount
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/hassos-supervisor.service
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/var-lib-NetworkManager.mount
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/var-lib-docker.mount
  buildroot-external/rootfs-overlay/usr/share/system-connections/default
  buildroot-external/scripts/rootfs-layer.sh
  buildroot-patches/0008-Fix-dhcp-client.patch
  buildroot/package/dhcp/dhcp.mk
Labels: REL-1, cla-signed, in progress

#82 Update supervisor 115
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
Labels: REL-1, cla-signed, in progress

#83 Reset if we can't boot
  buildroot-external/board/raspberrypi/rpi3-64/uboot-boot.sh
  buildroot-external/board/raspberrypi/uboot-boot.sh
Labels: REL-1, cla-signed, in progress

#84 Some cleanup
  buildroot-external/rootfs-overlay/etc/systemd/system/dropbear.service.d/nm.conf
  buildroot-external/rootfs-overlay/etc/systemd/system/multi-user.target.wants/hassos-apparmor.service
  buildroot-external/rootfs-overlay/etc/systemd/system/multi-user.target.wants/hassos-bind.target
  buildroot-external/rootfs-overlay/etc/systemd/system/multi-user.target.wants/hassos-config.service
  buildroot-external/rootfs-overlay/etc/systemd/system/multi-user.target.wants/hassos-supervisor.service
  buildroot-external/rootfs-overlay/etc/systemd/system/multi-user.target.wants/hassos-zram.target
Labels: REL-1, cla-signed, in progress

#86 Add powersave config to network manager
  Documentation/network.md
Labels: Documentation, cla-signed, in progress

#88 Fix time on overlay
  buildroot-external/misc/rauc-hook
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-timesyncd.service.d/hassos.conf
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-timesyncd.service.d/ro.conf
Labels: REL-1, cla-signed, in progress

#90 Check simlink
  buildroot-external/misc/rauc-hook
Labels: cla-signed, in progress

#91 Native bluetooth support
  buildroot-external/Config.in
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/package/bluetooth-bcm43xx/Config.in
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.mk
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.service
  buildroot-external/rootfs-overlay/etc/bluetooth/main.conf
  buildroot-external/rootfs-overlay/etc/systemd/system/hassos-bind.target.wants/var-lib-bluetooth.mount
  buildroot-external/rootfs-overlay/etc/systemd/system/hassos-hardware.target.wants/.empty
  buildroot-external/rootfs-overlay/etc/systemd/system/multi-user.target.wants/hassos-hardware.target
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/hassos-hardware.target
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/var-lib-bluetooth.mount
Labels: REL-1, cla-signed, in progress

#92 Update bluetooth docs & add udev rules
  Documentation/bluetooth.md
  buildroot-external/busybox.config
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.mk
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.rules
Labels: cla-signed, in progress

#94 Fix boot menu
  buildroot-external/bootloader/barebox/menu/10-boot-A/action
  buildroot-external/bootloader/barebox/menu/20-boot-B/action
Labels: cla-signed, in progress

#95 Update Documentation
  Documentation/boards/raspberrypi.md
  Documentation/deployment.md
Labels: REL-1, cla-signed, in progress

#98 Update rpi kernel 4.14.54 / Firmware / wifi
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.mk
  buildroot-patches/0006-Pump-raspberry-pi-firmware-for-kernel-4.14.patch
  buildroot-patches/0010-rpi-use-latest-wifi-driver.patch
  buildroot/package/rpi-firmware/rpi-firmware.hash
  buildroot/package/rpi-firmware/rpi-firmware.mk
  buildroot/package/rpi-wifi-firmware/rpi-wifi-firmware.hash
  buildroot/package/rpi-wifi-firmware/rpi-wifi-firmware.mk
  scripts/update-rpi-kernel.sh
Labels: REL-1, cla-signed, in progress

#99 Fix handling with resolv.conf
  buildroot-external/rootfs-overlay/etc/resolv.conf
  buildroot-external/rootfs-overlay/etc/tmpfiles.d/nm.conf
Labels: REL-1, cla-signed, in progress

#103 Raspberry Pi node of 64bit
  Documentation/boards/raspberrypi.md
Labels: REL-1, cla-signed, in progress

#107 Fix prevent device tree on rpi
  buildroot-external/board/raspberrypi/rpi3-64/uboot-boot.sh
  buildroot-external/board/raspberrypi/uboot-boot.sh
  buildroot-external/misc/rauc-hook
Labels: REL-1, cla-signed, in progress

#114 Update network.md
  Documentation/network.md
Labels: REL-1, cla-signed

#115 Allow more USB serial device on OVA
  buildroot-external/board/ova/kernel.config
Labels: REL-1, cla-signed, in progress

#118 Add support for VIRTIO
  buildroot-external/board/ova/kernel.config
Labels: cla-signed, in progress

#119 OVA: Fix serial support
  buildroot-external/board/ova/kernel.config
Labels: cla-signed, in progress

#124 fix wireless settings
  Documentation/network.md
Labels: REL-1, cla-signed, in progress

#137 OS: Update supervisor 121
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
Labels: REL-1, cla-signed, in progress

#132 OVA: Add support for Aeotec Zstick
  buildroot-external/board/ova/kernel.config
Labels: REL-1, cla-signed, in progress

#138 OVA: Update kernel to 4.14.59
  Documentation/kernel.md
  buildroot-external/configs/ova_defconfig
Labels: cla-signed, in progress

#139 rpi: Update kernel & firmware 4.14.58
  Documentation/kernel.md
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-patches/0006-Pump-raspberry-pi-firmware-for-kernel-4.14.patch
  buildroot/package/rpi-firmware/rpi-firmware.hash
  buildroot/package/rpi-firmware/rpi-firmware.mk
Labels: REL-1, cla-signed, in progress
