Repository home-assistant/operating-system, pull requests merged in 2019-07, with the labels that each got.

#423 Update ova.md
  Documentation/boards/ova.md
Labels: cla-signed

#425 Odroid xu4 updates
  buildroot-external/board/hardkernel/odroid-xu4/kernel.config
  buildroot-external/board/hardkernel/odroid-xu4/meta
  buildroot-external/board/hardkernel/odroid-xu4/patches/linux/000-arm-exynos_change_the_default_dma_coherent_pool_size.patch
  buildroot-external/board/hardkernel/odroid-xu4/patches/linux/000-odroid_xu4_modified_strobe_timing_for_emmc_hs400_mode.patch
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-patches/0010-odroid-ux4-firmware.patch
  buildroot/package/linux-firmware/Config.in
  buildroot/package/linux-firmware/linux-firmware.mk
Labels: cla-signed

#426 Raspberry Pi Firmware/Kernel update
  Documentation/kernel.md
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-patches/0004-rpi-firmware-Bump-firmware-for-kernel-4.19.patch
  buildroot/package/rpi-firmware/rpi-firmware.hash
  buildroot/package/rpi-firmware/rpi-firmware.mk
Labels: board/raspberrypi, cla-signed

#427 Update bootloader RPi
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
  scripts/update-uboot.sh
Labels: cla-signed

#431 Update Hass.io Supervisor
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/opi_prime_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed

#436 Fix defconfig name for rpi zero
  buildroot-external/configs/rpi0_w_defconfig
Labels: board/raspberrypi, cla-signed

#424 Note that disk controller must be SATA not SCSI.
  Documentation/boards/ova.md
Labels: Documentation, cla-signed

#440 rpi: Add USB boot support
  Documentation/boards/raspberrypi.md
  buildroot-external/board/raspberrypi/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot64.ush
  buildroot-external/board/raspberrypi/uboot.config
Labels: cla-signed
