Repository home-assistant/operating-system, pull requests merged in 2019-04, with the labels that each got.

#390 Adds universal TUN/TAP kernel support
  buildroot-external/kernel/hassos.config
Labels: cla-signed

#391 Update odroid-xu4.md to add additional eMMC instruction
  Documentation/boards/odroid-xu4.md
Labels: cla-signed, in progress

#395 Added Vmware specific kernel modules to support paravirtualized drivers
  buildroot-external/board/intel/ova/kernel.config
Labels: REL-2, cla-signed
