Repository home-assistant/operating-system, pull requests merged in 2019-02, with the labels that each got.

#338 Build: speedup uboot kernel load
  buildroot-external/scripts/hdd-image.sh
Labels: REL-2, cla-signed, in progress

#341 Odroid XU4: Use ondemand
  buildroot-external/board/hardkernel/odroid-xu4/kernel.config
Labels: REL-2, cla-signed, in progress

#348 OS: change zram swap to 25% of available memory
  buildroot-external/rootfs-overlay/usr/libexec/hassos-zram
Labels: in progress

#352 Documentation: Tinker eMMC
  Documentation/boards/tinker.md
Labels: cla-signed

#353 OVA: update kernel 4.19.20
  Documentation/kernel.md
  buildroot-external/configs/ova_defconfig
Labels: REL-2, cla-signed, in progress

#355 Fix ring buffer errors by applying ODroid Patch
  buildroot-external/board/hardkernel/odroid-xu4/patches/linux/000-arm-exynos_change_the_default_dma_coherent_pool_size.patch
Labels: REL-2, cla-signed

#359 Fix cve-2019-5736
  buildroot-external/patches/runc/0048-nsenter-clone-proc-self-exe-to-avoid-exposing-host-b.patch
  buildroot-external/patches/runc/0050-nsexec-CVE-2019-5736-avoid-parsing-environ.patch
  buildroot-patches/0001-docker-containerd-bump-to-v1.2.4.patch
  buildroot/package/docker-containerd/docker-containerd.hash
  buildroot/package/docker-containerd/docker-containerd.mk
Labels: REL-2, cla-signed, in progress

#360 Rpi: update kernel 4.14.98 42f1859
  Documentation/kernel.md
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-patches/0005-Pump-raspberry-pi-firmware-for-kernel-4.14.patch
  buildroot/package/rpi-firmware/rpi-firmware.hash
  buildroot/package/rpi-firmware/rpi-firmware.mk
Labels: REL-2, cla-signed, in progress

#362 Use github workflow to check scripts
  .github/main.workflow
Labels: cla-signed, in progress

#363 Fix workflow
  .github/main.workflow
  .travis.yml
  buildroot-external/scripts/rauc.sh
  buildroot-external/scripts/rootfs-layer.sh
Labels: cla-signed, in progress

#365 OS: Disable coredump
  buildroot-external/rootfs-overlay/etc/systemd/coredump.conf
Labels: REL-2, cla-signed, in progress
