Repository home-assistant/operating-system, pull requests merged in 2019-05, with the labels that each got.

#398 Add PROCPS_NG package to enable portainer stats
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/opi_prime_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed

#397 Adding /etc/modprobe.d folder for module configuration
  Documentation/configuration.md
  buildroot-external/rootfs-overlay/etc/modprobe.d/.empty
  buildroot-external/rootfs-overlay/etc/modules-load.d/.empty
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-modules-load.service.d/hassos.conf
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/etc-modprobe.d.mount
  buildroot-external/rootfs-overlay/usr/sbin/hassos-config
Labels: REL-2, cla-signed

#402 Version 3.1
  .github/release-drafter.yml
  .github/stale.yml
  .hadolint.yaml
  .travis.yml
  Dockerfile
  Documentation/boards/odroid-xu4.md
  Documentation/configuration.md
  azure-pipelines.yml
  buildroot-external/board/intel/ova/kernel.config
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/opi_prime_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/kernel/hassos.config
  buildroot-external/meta
  buildroot-external/rootfs-overlay/etc/modprobe.d/.empty
  buildroot-external/rootfs-overlay/etc/modules-load.d/.empty
  buildroot-external/rootfs-overlay/etc/systemd/coredump.conf
  buildroot-external/rootfs-overlay/etc/systemd/system/docker.service.d/hassos.conf
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-modules-load.service.d/hassos.conf
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/etc-modprobe.d.mount
  buildroot-external/rootfs-overlay/usr/sbin/hassos-config
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
  buildroot-external/scripts/rauc.sh
  buildroot-external/scripts/rootfs-layer.sh
Labels: cla-signed

#403 Change docker entry point script to allow additional commands
  .azure/Dockerfile
  scripts/entry.sh
Labels: build, cla-signed

#404 Update HassOS App to use alpine 3.9
  buildroot-external/package/hassos/builder/Dockerfile
Labels: cla-signed

#405 Support build as user
  Dockerfile
  scripts/enter.sh
  scripts/entry.sh
Labels: build, cla-signed

#406 Lint hostapp.sh and robust umount
  buildroot-external/package/hassos/builder/Dockerfile
  buildroot-external/package/hassos/builder/hostapp.sh
  buildroot-external/package/hassos/hassos.mk
  buildroot-external/scripts/hdd-image.sh
  scripts/entry.sh
Labels: cla-signed

#400 ID parameter in file have to be the same as name of file
  Documentation/network.md
Labels: Documentation, cla-signed

#408 Add cifs support
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os
