Repository home-assistant/operating-system, pull requests merged in 2020-11, with the labels that each got.

#948 Use upstream ODROID N2+ support and CDC ACM cooldown fix
  buildroot-external/board/hardkernel/patches/linux/0001-Revert-cdc-acm-introduce-a-cool-down.patch
  buildroot-external/board/hardkernel/patches/linux/0001-arm64-defconfig-enable-meson-gx-audio-as-module.patch
  buildroot-external/board/hardkernel/patches/linux/0002-ASoC-meson-imply-acodec-glue-on-axg-sound-card.patch
  buildroot-external/board/hardkernel/patches/linux/0003-ASoC-meson-gx-card-fix-sound-dai-dt-schema.patch
  buildroot-external/board/hardkernel/patches/linux/0004-arm64-dts-meson-g12-add-internal-DAC.patch
  buildroot-external/board/hardkernel/patches/linux/0005-arm64-dts-meson-g12-add-internal-DAC-glue.patch
  buildroot-external/board/hardkernel/patches/linux/0006-arm64-dts-meson-g12b-odroid-n2-enable-audio-loopback.patch
  buildroot-external/board/hardkernel/patches/linux/0007-arm64-dts-meson-odroid-n2-add-jack-audio-output-supp.patch
  buildroot-external/board/hardkernel/patches/linux/0008-dt-bindings-arm-amlogic-add-support-for-the-ODROID-N.patch
  buildroot-external/board/hardkernel/patches/linux/0009-arm64-dts-meson-convert-ODROID-N2-to-dtsi.patch
  buildroot-external/board/hardkernel/patches/linux/0010-arm64-dts-meson-add-support-for-the-ODROID-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0011-arm64-dts-meson-add-missing-g12-rng-clock.patch
  buildroot-external/board/hardkernel/patches/linux/0012-arm64-dts-meson-odroid-n2-plus-fix-vddcpu_a-pwm.patch
  buildroot-external/board/hardkernel/patches/linux/0013-clk-meson-g12a-mark-fclk_div2-as-critical.patch
  buildroot-external/board/hardkernel/patches/linux/0014-usb-cdc-acm-fix-cooldown-mechanism.patch
Labels: cla-signed

#949 Add machine specific landingpage container at build time
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/package/hassio/Config.in
  buildroot-external/package/hassio/builder/hostapp.sh
  buildroot-external/package/hassio/hassio.mk
Labels: REL-4, cla-signed

#937 reboot kernels on panic so u-boot can fallback to previous update
  buildroot-external/kernel/hassos.config
Labels: cla-signed, hacktoberfest-accepted

#952 Simplify self healing capabilities of Supervisor service
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/hassos-supervisor.service
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed

#954 RaspberryPi: Update firmware 2ba11f2a07760588546821aed578010252c9ecb3
  buildroot-patches/0002-rpi-firmware-Bump-firmware.patch
  buildroot/package/rpi-firmware/rpi-firmware.hash
  buildroot/package/rpi-firmware/rpi-firmware.mk
Labels: cla-signed

#936 use GPT partition table for rpi4
  buildroot-external/board/raspberrypi/rpi4-64/meta
  buildroot-external/board/raspberrypi/rpi4/meta
Labels: cla-signed, hacktoberfest-accepted

#957 Move RuntimeDirectory to the Service section
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/hassos-supervisor.service
Labels: cla-signed

#926 Support Odroid C4 SBC
  Documentation/boards/README.md
  Documentation/boards/hardkernel/README.md
  Documentation/boards/hardkernel/odroid-c4.md
  Documentation/development.md
  Documentation/kernel.md
  azure-pipelines-release.yml
  buildroot-external/board/hardkernel/odroid-c4/hassos-hook.sh
  buildroot-external/board/hardkernel/odroid-c4/meta
  buildroot-external/board/hardkernel/odroid-c4/patches/uboot/0001-HACK-mmc-meson-gx-limit-to-24MHz.patch
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/uboot.config
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/package/hardkernel-boot/Config.in
  buildroot-external/package/hardkernel-boot/hardkernel-boot.mk
Labels: cla-signed, hacktoberfest-accepted

#958 Update ODROID N2 U-Boot reference to get latest DDR timings
  buildroot-external/package/hardkernel-boot/hardkernel-boot.mk
Labels: REL-4, cla-signed

#961 Update ODROID-N2 binary blobs to those built with latest U-Boot
  buildroot-external/package/hardkernel-boot/hardkernel-boot.mk
Labels: REL-4, cla-signed

#962 Fix CDC ACM error recovery in Raspberry Pi kernels as well (#940)
  buildroot-external/board/raspberrypi/patches/linux/0001-brcmfmac-add-FT-based-AKMs-in-brcmf_set_key_mgmt-for.patch
  buildroot-external/board/raspberrypi/patches/linux/0002-CDC-ACM-heed-quirk-also-in-error-handling.patch
  buildroot-external/board/raspberrypi/patches/linux/0003-usb-cdc-acm-fix-cooldown-mechanism.patch
Labels: cla-signed

#964 Linux: Update kernel 5.4.75
  Documentation/kernel.md
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed

#967 Fix configuration.md link in raspberrypi README.md
  Documentation/boards/raspberrypi/README.md
Labels: cla-signed

#969 Revert "use GPT partition table for RPi4 (#936)"
  buildroot-external/board/raspberrypi/rpi4-64/meta
  buildroot-external/board/raspberrypi/rpi4/meta
Labels: cla-signed

#963 ODROID-C4 fixes
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/package/hardkernel-boot/hardkernel-boot.mk
Labels: cla-signed

#960 Make self healing capabilities more robust
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/hassos-supervisor.service
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed

#973 Use performance governor to avoid frequency scaling
  buildroot-external/board/hardkernel/odroid-n2/kernel.config
  buildroot-external/configs/odroid_n2_defconfig
Labels: REL-4, cla-signed

#976 ODROID: Update kernel 5.9.6
  Documentation/kernel.md
  buildroot-external/board/hardkernel/patches/linux/0007-usb-cdc-acm-fix-cooldown-mechanism.patch
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
Labels: cla-signed

#978 Move patch for the RPi Linux kernel to the correct location
  buildroot-external/board/raspberrypi/patches/linux/0008-ARM-dts-bcm283x-add-compatible-picked-up-by-U-Boot.patch
Labels: cla-signed

#979 Enable scp client
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed

#988 Drop services we don't offer
  buildroot-external/scripts/rootfs-layer.sh
Labels: REL-4

#989 Linux: Update kernel 5.4.77
  Documentation/kernel.md
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed

#986 Use systemd-resolved to announce hostname via mDNS and LLMNR
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/rootfs-overlay/etc/NetworkManager/system-connections/default
  buildroot-external/rootfs-overlay/etc/avahi/avahi-daemon.conf
  buildroot-external/rootfs-overlay/usr/lib/systemd/dnssd/workstation.dnssd
  buildroot-external/scripts/rootfs-layer.sh
Labels: cla-signed

#991 Fix wireguard-linux-compat for latest stable kernels
  buildroot-patches/0001-Bump-wireguard-linux-compat-to-work-with-latest-kern.patch
  buildroot/package/wireguard-linux-compat/wireguard-linux-compat.hash
  buildroot/package/wireguard-linux-compat/wireguard-linux-compat.mk
Labels: cla-signed

#996 Use upstream fix for zram on 32-bit ARM with LPAE (RPi4)
  buildroot-external/board/raspberrypi/patches/linux/0001-dt-bindings-arm-bcm-Convert-BCM2835-firmware-binding.patch
  buildroot-external/board/raspberrypi/patches/linux/0002-dt-bindings-clock-Add-a-binding-for-the-RPi-Firmware.patch
  buildroot-external/board/raspberrypi/patches/linux/0003-dt-bindings-arm-bcm-Add-a-select-to-the-RPI-Firmware.patch
  buildroot-external/board/raspberrypi/patches/linux/0004-dt-bindings-reset-Add-a-binding-for-the-RPi-Firmware.patch
  buildroot-external/board/raspberrypi/patches/linux/0005-ARM-dts-bcm2711-Add-firmware-usb-reset-node.patch
  buildroot-external/board/raspberrypi/patches/linux/0006-ARM-dts-bcm2711-Add-reset-controller-to-xHCI-node.patch
  buildroot-external/board/raspberrypi/patches/linux/0007-arch-pgtable-define-MAX_POSSIBLE_PHYSMEM_BITS-where-.patch
  buildroot-external/board/raspberrypi/patches/linux/0007-mm-zsmalloc-include-sparsemem.h-for-MAX_PHYSMEM_BITS.patch
  buildroot-external/board/raspberrypi/patches/linux/0008-ARM-dts-bcm283x-add-compatible-picked-up-by-U-Boot.patch
Labels: cla-signed

#998 Improve release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: build, cla-signed

#999 Add on-board RTC support for ODROID-N2+
  buildroot-external/board/hardkernel/kernel-amlogic.config
  buildroot-external/board/hardkernel/patches/linux/0008-arm64-dts-meson-add-RTC-to-ODROID-N2-boards.patch
Labels: board/odroid, cla-signed

#1001 Fix U-Boot environment handling
  buildroot-external/patches/uboot-tools/0001-fw_printenv-use-run-as-default-location-for-lock-fil.patch
  buildroot-external/rootfs-overlay/usr/libexec/hassos-persists
Labels: bug, cla-signed

#1002 Set permissions for builder on entry
  scripts/entry.sh
Labels: REL-4, build, cla-signed

#1003 Fix shellcheck warnings
  buildroot-external/board/intel/ova/hassos-hook.sh
  buildroot-external/package/bluetooth-rtl8723/bluetooth-rtl8723
Labels: cla-signed

#1004 Fix DNS resolving
  buildroot-external/rootfs-overlay/etc/systemd/resolved.conf
  buildroot-external/scripts/rootfs-layer.sh
Labels: cla-signed

#1005 Use GitHub Actions
  .github/workflows/pr-checks.yml
  .github/workflows/release.yml
  azure-pipelines-ci.yml
  azure-pipelines-release.yml
Labels: cla-signed

#1007 Make sure ALSA modprobe parameters get applied
  buildroot-external/busybox.config
  buildroot-external/rootfs-overlay/usr/lib/modprobe.d/alsa-base.conf
Labels: cla-signed, os

#1008 Improve issue reporting template
  .github/ISSUE_TEMPLATE.md
Labels: build, cla-signed

#1009 Increase OVA disk image default size to 32GB
  buildroot-external/board/intel/ova/meta
Labels: board/ova, cla-signed

#1015 Fix N2+ boot by disabling USB enumeration
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-n2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
Labels: cla-signed

#1016 Avoid trying to boot non-existing kernel image in failover case
  buildroot-external/board/asus/tinker/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-n2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot64.ush
Labels: REL-4, board/odroid, board/raspberrypi, board/tinker, cla-signed

#1017 Add dev build workflow
  .github/workflows/dev.yml
  Makefile
  README.md
  buildroot-external/scripts/name.sh
  buildroot-external/scripts/post-build.sh
Labels: cla-signed

#1019 Linux: Update kernel 5.4.80
  Documentation/kernel.md
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed

#1018 Compress images using xz instead of gzip
  buildroot-external/board/asus/hassos-hook.sh
  buildroot-external/board/hardkernel/odroid-c2/hassos-hook.sh
  buildroot-external/board/hardkernel/odroid-c4/hassos-hook.sh
  buildroot-external/board/hardkernel/odroid-n2/hassos-hook.sh
  buildroot-external/board/hardkernel/odroid-xu4/hassos-hook.sh
  buildroot-external/board/intel/nuc/hassos-hook.sh
  buildroot-external/board/intel/ova/hassos-hook.sh
  buildroot-external/board/raspberrypi/hassos-hook.sh
  buildroot-external/scripts/hdd-image.sh
Labels: build, cla-signed

#939 Add rpi-eeprom firmware
  buildroot-external/Config.in
  buildroot-external/board/raspberrypi/hassos-hook.sh
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/package/rpi-eeprom/Config.in
  buildroot-external/package/rpi-eeprom/rpi-eeprom.mk
Labels: cla-signed, hacktoberfest-accepted

#1020 Add sub-directory per development build
  .github/workflows/dev.yml
Labels: build, cla-signed

#1021 Bump dev channel after build
  .github/workflows/release.yml
Labels: cla-signed

#1022 Fix boot from USB for Raspberry Pi 32-bit installations (#987)
  buildroot-external/board/raspberrypi/patches/uboot/0001-rpi-Use-CONFIG_OF_BOARD-instead-of-CONFIG_EMBED.patch
  buildroot-external/board/raspberrypi/patches/uboot/0002-raspberrypi-Disable-simple-framebuffer-support.patch
  buildroot-external/board/raspberrypi/patches/uboot/0003-rpi-force-a-smaller-amount-of-memory.patch
Labels: board/raspberrypi, cla-signed

#1023 RaspberryPi: Update kernel 5.4.79 - 9797f1a4938c20139b00a25de93cc99efb5c291b
  Documentation/kernel.md
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
Labels: board/raspberrypi, cla-signed

#1025 Raspberry Pi: Add RPi400 and CM4 support
  buildroot-external/board/raspberrypi/patches/uboot/0001-rpi-Use-CONFIG_OF_BOARD-instead-of-CONFIG_EMBED.patch
  buildroot-external/board/raspberrypi/patches/uboot/0002-raspberrypi-Disable-simple-framebuffer-support.patch
  buildroot-external/board/raspberrypi/patches/uboot/0003-rpi-force-a-smaller-amount-of-memory.patch
  buildroot-external/board/raspberrypi/patches/uboot/0004-usb-xhci-convert-to-TRB_TYPE.patch
  buildroot-external/board/raspberrypi/patches/uboot/0005-usb-xhci-use-macros-with-parameter-to-fill-ep_info2.patch
  buildroot-external/board/raspberrypi/patches/uboot/0006-usb-xhci-avoid-type-conversion-of-void.patch
  buildroot-external/board/raspberrypi/patches/uboot/0007-mmc-sdhci-move-the-ADMA2-table-handling-into-own-mod.patch
  buildroot-external/board/raspberrypi/patches/uboot/0008-rpi-Add-identifier-for-the-new-RPi400.patch
  buildroot-external/board/raspberrypi/patches/uboot/0009-rpi-Add-identifier-for-the-new-CM4.patch
  buildroot-external/board/raspberrypi/patches/uboot/0010-pci-pcie-brcmstb-Fix-inbound-window-configurations.patch
  buildroot-external/board/raspberrypi/patches/uboot/0011-dm-Introduce-xxx_get_dma_range.patch
  buildroot-external/board/raspberrypi/patches/uboot/0012-dm-Introduce-DMA-constraints-into-the-core-device-mo.patch
  buildroot-external/board/raspberrypi/patches/uboot/0013-dm-Introduce-dev_phys_to_bus-dev_bus_to_phys.patch
  buildroot-external/board/raspberrypi/patches/uboot/0014-xhci-translate-virtual-addresses-into-the-bus-s-addr.patch
  buildroot-external/board/raspberrypi/patches/uboot/0015-mmc-Introduce-mmc_phys_to_bus-mmc_bus_to_phys.patch
Labels: board/raspberrypi, cla-signed

#1026 Fix boot script issues (#1024)
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot64.ush
Labels: REL-4, board/odroid, board/raspberrypi, cla-signed

#1030 Improve OVF descriptor
  buildroot-external/board/intel/ova/home-assistant.ovf
Labels: cla-signed

#1031 Fix ODROID-N2(+) SoC version banner
  buildroot-external/board/hardkernel/patches/uboot/0001-ARM-meson-isolate-loading-of-socinfo.patch
  buildroot-external/board/hardkernel/patches/uboot/0002-meson-Add-board_rev-to-env.patch
Labels: board/odroid, cla-signed

#1034 Build fixes for Pre-Release 5.6
  .github/workflows/release.yml
Labels: cla-signed

#1036 Fix Barebox Environment handling
  buildroot-external/board/intel/patches/dt-utils/0001-barebox-state-get-devicetree-from-file.patch
  buildroot-external/board/intel/patches/dt-utils/0002-libdt-support-finding-devices-by-partuuid.patch
  buildroot-external/board/intel/patches/dt-utils/0003-state-use-run-to-store-lockfile.patch
Labels: board/intel-nuc, board/ova, cla-signed
