Repository home-assistant/operating-system, pull requests merged in 2021-03, with the labels that each got.

#1250 Update Bluetooth firmware for CYW43455 (Raspberry Pi 3 B+/4)
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.mk
Labels: REL-5, board/raspberrypi, cla-signed

#1247 Use rauc hook to extend compatible for upcomming OS release 6
  buildroot-external/ota/rauc-hook
  buildroot-external/scripts/ota.sh
Labels: REL-5, cla-signed, os-update

#1248 Add Ralink rt27xx/rt28xx/rt30xx firmware (#1242)
  buildroot-external/board/asus/tinker/kernel.config
  buildroot-external/board/hardkernel/kernel-amlogic.config
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi_defconfig
Labels: board/odroid, board/raspberrypi, cla-signed

#1258 Update Raspberry Pi to Linux 5.10 (raspberrypi-kernel_1.20210201-1)
  buildroot-external/board/raspberrypi/patches/linux/0001-ARM-dts-bcm283x-add-compatible-picked-up-by-U-Boot.patch
  buildroot-external/board/raspberrypi/patches/linux/0001-dt-bindings-arm-bcm-Convert-BCM2835-firmware-binding.patch
  buildroot-external/board/raspberrypi/patches/linux/0002-dt-bindings-clock-Add-a-binding-for-the-RPi-Firmware.patch
  buildroot-external/board/raspberrypi/patches/linux/0003-dt-bindings-arm-bcm-Add-a-select-to-the-RPI-Firmware.patch
  buildroot-external/board/raspberrypi/patches/linux/0004-dt-bindings-reset-Add-a-binding-for-the-RPi-Firmware.patch
  buildroot-external/board/raspberrypi/patches/linux/0005-ARM-dts-bcm2711-Add-firmware-usb-reset-node.patch
  buildroot-external/board/raspberrypi/patches/linux/0006-ARM-dts-bcm2711-Add-reset-controller-to-xHCI-node.patch
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
Labels: board/raspberrypi

#1261 Remove the no longer required busybox-acpid service
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/busybox-acpid.service
Labels: board/intel-nuc, board/ova, cla-signed

#1263 Adding gasket/apex kernel modules
  buildroot-external/kernel/device-support.config
Labels: cla-signed

#1209 Rename Intel NUC machine to Generic x86-64
  Documentation/boards/README.md
  Documentation/boards/generic-x86-64/README.md
  Documentation/boards/intel/README.md
  Documentation/kernel.md
  buildroot-external/board/pc/barebox.config
  buildroot-external/board/pc/generic-x86-64/hassos-hook.sh
  buildroot-external/board/pc/generic-x86-64/kernel.config
  buildroot-external/board/pc/generic-x86-64/meta
  buildroot-external/board/pc/ova/hassos-hook.sh
  buildroot-external/board/pc/ova/home-assistant.ovf
  buildroot-external/board/pc/ova/kernel.config
  buildroot-external/board/pc/ova/meta
  buildroot-external/board/pc/patches/dt-utils/0001-barebox-state-get-devicetree-from-file.patch
  buildroot-external/board/pc/patches/dt-utils/0002-libdt-support-finding-devices-by-partuuid.patch
  buildroot-external/board/pc/patches/dt-utils/0003-state-use-run-to-store-lockfile.patch
  buildroot-external/board/pc/patches/rauc/0001-add-i-argument-to.patch
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/ova_defconfig
  scripts/update-kernel-upstream.sh
Labels: cla-signed

#1213 Rename hassos to haos
  Makefile
  buildroot-external/meta
  buildroot-external/ota/rauc-hook
  buildroot-external/scripts/ota.sh
  buildroot-external/scripts/post-build.sh
Labels: cla-signed, os

#1265 Accept installation with intel-nuc in compatible string
  buildroot-external/ota/rauc-hook
Labels: cla-signed, os-update

#1267 Complete rename to generic-x86-64
  .github/ISSUE_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/dev.yml
  .github/workflows/release.yml
Labels: build, cla-signed

#1269 Add OS agent
  buildroot-external/Config.in
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/package/os-agent/Config.in
  buildroot-external/package/os-agent/os-agent.mk
  buildroot-external/rootfs-overlay/usr/bin/datactl
Labels: cla-signed, os

#1276 Clarify network configuration support
  Documentation/network.md
Labels: cla-signed

#1275 Bump to U-Boot 2021.04-rc4
  buildroot-external/board/asus/tinker/patches/uboot/0001-SPL-modify-load-address-of-U-Boot.patch
  buildroot-external/board/asus/tinker/patches/uboot/0002-rockchip-dts-tinker-move-i2c-node-to-shared-device-t.patch
  buildroot-external/board/asus/tinker/patches/uboot/0003-rockchip-dts-tinker-remove-unnecessary-node.patch
  buildroot-external/board/asus/tinker/patches/uboot/0004-pmic-enable-LDO2-vcc33_mipi-at-bootup.patch
  buildroot-external/board/hardkernel/patches/uboot/0001-ARM-meson-isolate-loading-of-socinfo.patch
  buildroot-external/board/hardkernel/patches/uboot/0002-meson-Add-board_rev-to-env.patch
  buildroot-external/board/hardkernel/patches/uboot/0003-HACK-mmc-meson-gx-limit-to-24MHz.patch
  buildroot-external/board/hardkernel/patches/uboot/0004-pinctrl-meson-fix-bit-manipulation-of-pin-bias-confi.patch
  buildroot-external/board/raspberrypi/patches/uboot/0001-rpi-Use-CONFIG_OF_BOARD-instead-of-CONFIG_EMBED.patch
  buildroot-external/board/raspberrypi/patches/uboot/0002-raspberrypi-Disable-simple-framebuffer-support.patch
  buildroot-external/board/raspberrypi/patches/uboot/0003-rpi-force-a-smaller-amount-of-memory.patch
  buildroot-external/board/raspberrypi/patches/uboot/0004-usb-xhci-convert-to-TRB_TYPE.patch
  buildroot-external/board/raspberrypi/patches/uboot/0005-usb-xhci-use-macros-with-parameter-to-fill-ep_info2.patch
  buildroot-external/board/raspberrypi/patches/uboot/0006-usb-xhci-xhci_bulk_tx-Don-t-BUG-when-comparing-addre.patch
  buildroot-external/board/raspberrypi/patches/uboot/0007-usb-xhci-avoid-type-conversion-of-void.patch
  buildroot-external/board/raspberrypi/patches/uboot/0008-mmc-sdhci-move-the-ADMA2-table-handling-into-own-mod.patch
  buildroot-external/board/raspberrypi/patches/uboot/0009-rpi-Add-identifier-for-the-new-RPi400.patch
  buildroot-external/board/raspberrypi/patches/uboot/0010-rpi-Add-identifier-for-the-new-CM4.patch
  buildroot-external/board/raspberrypi/patches/uboot/0011-pci-pcie-brcmstb-Fix-inbound-window-configurations.patch
  buildroot-external/board/raspberrypi/patches/uboot/0012-dm-Introduce-xxx_get_dma_range.patch
  buildroot-external/board/raspberrypi/patches/uboot/0013-dm-Introduce-DMA-constraints-into-the-core-device-mo.patch
  buildroot-external/board/raspberrypi/patches/uboot/0014-dm-Introduce-dev_phys_to_bus-dev_bus_to_phys.patch
  buildroot-external/board/raspberrypi/patches/uboot/0015-xhci-translate-virtual-addresses-into-the-bus-s-addr.patch
  buildroot-external/board/raspberrypi/patches/uboot/0016-mmc-Introduce-mmc_phys_to_bus-mmc_bus_to_phys.patch
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: board/odroid, board/raspberrypi, board/tinker, cla-signed, u-boot

#1279 Remove unnecessary avahi-daemon.service configs
  buildroot-external/rootfs-overlay/etc/systemd/system/avahi-daemon.service.d/hassos.conf
  buildroot-external/rootfs-overlay/etc/systemd/system/avahi-daemon.service.d/nm.conf
Labels: cla-signed

#1277 Rename NetworkManager default profile
  Documentation/network.md
  buildroot-external/rootfs-overlay/etc/NetworkManager/system-connections/default
Labels: cla-signed

#1278 Restore AppArmor profile when not present on the system
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/rootfs-overlay/usr/libexec/hassos-apparmor
Labels: cla-signed

#1283 Enable Realtek Bluetooth firmwares
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-patches/0006-package-linux-firmware-add-RTL87XX-RTL88XX-Bluetooth.patch
  buildroot/package/linux-firmware/Config.in
  buildroot/package/linux-firmware/linux-firmware.mk
Labels: board/generic-x86-64, board/odroid, board/ova, board/raspberrypi, board/tinker, cla-signed

#1284 Add udisks2 dameon and udisks2 OS agent support
  buildroot-external/Config.in
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/package/os-agent/os-agent.mk
  buildroot-external/package/udisks2/0001-Isolate-authorization-specific-functions-into-new-co.patch
  buildroot-external/package/udisks2/0002-Make-polkit-dependency-optional.patch
  buildroot-external/package/udisks2/0003-Avoid-autoreconf-error-if-introspection-macros-are-n.patch
  buildroot-external/package/udisks2/Config.in
  buildroot-external/package/udisks2/udisks2.hash
  buildroot-external/package/udisks2/udisks2.mk
Labels: cla-signed

#1286 Improve dropbear.service to avoid failed state after stop
  buildroot-external/rootfs-overlay/etc/systemd/system/dropbear.service.d/hassos.conf
Labels: cla-signed

#1287 Only start the HA CLI if we are in the default.target
  buildroot-external/rootfs-overlay/usr/sbin/hassos-cli
Labels: cla-signed

#1290 Update datactl move documentation
  Documentation/partition.md
Labels: cla-signed

#1292 Bump to latest OS Agent version to support Device Wipe
  buildroot-external/package/os-agent/os-agent.mk
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/haos-wipe.service
Labels: cla-signed, os
