Repository home-assistant/operating-system, pull requests merged in 2021-11, with the labels that each got.

#1623 Compile Btrfs support as a module
  buildroot-external/kernel/hassos.config
Labels: cla-signed, hacktoberfest-accepted

#1622 Simplify AppArmor with new OS-Agent SU
  buildroot-external/rootfs-overlay/usr/libexec/hassos-apparmor
Labels: cla-signed, hacktoberfest-accepted, REL-6

#1627 Expose systemd-journal-gatewayd to Supervisor
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/hassos-supervisor.service
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/systemd-journal-gatewayd.socket
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed, os

#1631 Add label action workflow
  .github/label-actions.yml
  .github/workflows/label-actions.yml
Labels: cla-signed

#1637 Use GitHub issue form
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla-signed

#1638 Drop Raspberry Pi 1/Zero W support
  .github/workflows/matrix.json
  .github/workflows/release.yml
  buildroot-external/board/raspberrypi/rpi/meta
  buildroot-external/board/raspberrypi/rpi0-w/meta
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi_defconfig
Labels: cla-signed

#1642 Linux: Update kernel 5.10.78
  Documentation/kernel.md
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, kernel, linux

#1648 Bump OS release version to 8
  buildroot-external/meta
Labels: cla-signed, os

#1649 Update Linux kernel patches for Home Assistant Amber
  buildroot-external/board/raspberrypi/amber/patches/linux/0001-ARM-dts-bcm2711-Add-device-tree-for-Home-Assistant-A.patch
  buildroot-external/board/raspberrypi/amber/patches/linux/0002-ARM-dts-bcm2711-amber-Mux-UART4-for-SiLabs-radio-mod.patch
  buildroot-external/board/raspberrypi/amber/patches/linux/0003-ARM-dts-bcm2711-amber-Mux-debug-UART5.patch
  buildroot-external/board/raspberrypi/amber/patches/linux/0004-ARM-dts-bcm2711-amber-Enable-I2C6-by-default.patch
  buildroot-external/board/raspberrypi/amber/patches/linux/0005-ARM-dts-bcm2711-amber-add-I2S-audio-codec.patch
  buildroot-external/board/raspberrypi/amber/patches/linux/0006-ARM-dts-bcm2711-amber-enable-GPIO-keys.patch
  buildroot-external/board/raspberrypi/amber/patches/linux/0007-ARM-dts-bcm2711-amber-add-user-LED.patch
  buildroot-external/board/raspberrypi/amber/patches/linux/0008-ARM-dts-bcm2711-amber-Add-NXP-PCF85063A-RTC.patch
Labels: cla-signed, board/amber

#1651 Enable Broadcom and Atheros Ethernet drivers (#1650)
  buildroot-external/board/pc/generic-x86-64/kernel.config
Labels: cla-signed, os, REL-7
