Repository home-assistant/operating-system, pull requests merged in 2021-09, with the labels that each got.

#1516 updated generic_raw_uart to latest 1.20 version
  buildroot-external/package/generic_raw_uart/generic_raw_uart.hash
  buildroot-external/package/generic_raw_uart/generic_raw_uart.mk
Labels: cla-signed, REL-6

#1517 updated eq3_char_loop and rpi-rf-mod package to latest versions
  buildroot-external/package/eq3_char_loop/eq3_char_loop.hash
  buildroot-external/package/eq3_char_loop/eq3_char_loop.mk
  buildroot-external/package/rpi-rf-mod/rpi-rf-mod.hash
  buildroot-external/package/rpi-rf-mod/rpi-rf-mod.mk
Labels: cla-signed, REL-6

#1525 Increase minimal free memory for Raspberry Pis
  buildroot-external/board/raspberrypi/rootfs-overlay/etc/sysctl.d/98-rpi.conf
Labels: cla-signed, board/raspberrypi, REL-6

#1526 Add Mediatek MT7601U support (#1520)
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/kernel/device-support.config
Labels: cla-signed, os, REL-6

#1528 Linux: Update kernel 5.10.61 for ODROID-N2 (#1512)
  buildroot-external/board/hardkernel/patches/linux/0001-arm64-dts-meson-add-i2c3-rtc-nodes-and-rtc-aliases-t.patch
  buildroot-external/board/hardkernel/patches/linux/0002-arm64-dts-meson-add-saradc-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0003-arm64-dts-meson-add-GPIO-line-names-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0004-arm64-dts-meson-g12b-add-power-button-support.patch
  buildroot-external/board/hardkernel/patches/linux/0005-arm64-dts-meson-g12b-add-GPIO-fan-support.patch
  buildroot-external/board/hardkernel/patches/linux/0006-arm64-dts-meson-g12b-odroid-n2-add-fan-as-cooling-de.patch
  buildroot-external/board/hardkernel/patches/linux/0007-arm64-dts-meson-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/0008-arm64-dts-meson-add-i2c2-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0009-Revert-of-fdt-Make-sure-no-map-does-not-remove-alrea.patch
  buildroot-external/board/hardkernel/patches/linux/board-odroidc2-add-uartA-uartC.patch
  buildroot-external/board/hardkernel/patches/linux/general-meson64-i2cX-missing-pins.patch
  buildroot-external/board/hardkernel/patches/linux/hardkernel-0013-C4-arm64-dts-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/hardkernel-0021-C4-arm64-dts-add-i2c2-i2c3-node.patch
  buildroot-external/configs/odroid_n2_defconfig
  scripts/update-kernel-upstream.sh
Labels: cla-signed, board/odroid, REL-6

#1529 Fix U-Boot USB initialization failure (#1203, #1490)
  buildroot-external/board/raspberrypi/patches/uboot/0001-rpi-Use-CONFIG_OF_BOARD-instead-of-CONFIG_EMBED.patch
  buildroot-external/board/raspberrypi/patches/uboot/0002-raspberrypi-Disable-simple-framebuffer-support.patch
  buildroot-external/board/raspberrypi/patches/uboot/0003-ARM-bcm283x-change-the-virtual-address-of-the-XHCI-P.patch
Labels: cla-signed, board/raspberrypi, REL-6

#1523 Add a buildroot utils/check-package linter check to pr-checks.yml
  .github/workflows/pr-checks.yml
  buildroot-external/package/bluetooth-rtl8723/Config.in
  buildroot-external/package/eq3_char_loop/0001-Makefile.patch
  buildroot-external/package/eq3_char_loop/0002-version1_1.patch
  buildroot-external/package/eq3_char_loop/eq3_char_loop.mk
  buildroot-external/package/generic_raw_uart/0001-kernel-Makefile.patch
  buildroot-external/package/generic_raw_uart/Config.in
  buildroot-external/package/generic_raw_uart/generic_raw_uart.mk
  buildroot-external/package/hardkernel-boot/hardkernel-boot.mk
  buildroot-external/package/intel-e1000e/Config.in
  buildroot-external/package/khadas-boot/khadas-boot.mk
  buildroot-external/package/qemu-guest-agent/Config.in
  buildroot-external/package/rpi-eeprom/rpi-eeprom.mk
  buildroot-external/package/rpi-firmware/rpi-firmware.mk
  buildroot-external/package/rpi-rf-mod/Config.in
  buildroot-external/package/rpi-rf-mod/rpi-rf-mod.mk
  buildroot-external/package/rtl8812au/Config.in
  buildroot-external/package/udisks2/0001-Allow-to-explicitly-disable-libsystemd-login.patch
  buildroot-external/package/udisks2/0001-Isolate-authorization-specific-functions-into-new-co.patch
  buildroot-external/package/udisks2/0002-Make-polkit-dependency-optional.patch
  buildroot-external/package/udisks2/0003-Avoid-autoreconf-error-if-introspection-macros-are-n.patch
  buildroot-external/package/udisks2/Config.in
  buildroot-external/package/xe-guest-utilities/Config.in
Labels: cla-signed, build

#1527 Add USB DS9490R 1-wire master support (#1513)
  buildroot-external/kernel/device-support.config
Labels: cla-signed, os

#1536 Linux: Update kernel 5.10.62
  Documentation/kernel.md
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, REL-6, board/generic-x86-64, board/khadas

#1541 Fix buffer overflow when initialize USB keyboard in U-Boot (#1538)
  buildroot-external/board/raspberrypi/patches/uboot/0001-rpi-Use-CONFIG_OF_BOARD-instead-of-CONFIG_EMBED.patch
  buildroot-external/board/raspberrypi/patches/uboot/0002-raspberrypi-Disable-simple-framebuffer-support.patch
  buildroot-external/board/raspberrypi/patches/uboot/0003-ARM-bcm283x-change-the-virtual-address-of-the-XHCI-P.patch
  buildroot-external/board/raspberrypi/patches/uboot/0004-IOMUX-Fix-buffer-overflow-in-iomux_replace_device.patch
Labels: cla-signed, board/raspberrypi

#1547 Wait until Internet is available before starting AppArmor
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/hassos-apparmor.service
Labels: cla-signed, os

#1548 Fix hybrid spelling
  buildroot-external/board/asus/tinker/meta
  buildroot-external/board/raspberrypi/rpi/meta
  buildroot-external/board/raspberrypi/rpi0-w/meta
  buildroot-external/board/raspberrypi/rpi2/meta
  buildroot-external/board/raspberrypi/rpi3-64/meta
  buildroot-external/board/raspberrypi/rpi3/meta
  buildroot-external/board/raspberrypi/rpi4-64/meta
  buildroot-external/board/raspberrypi/rpi4/meta
  buildroot-external/scripts/hdd-image.sh
Labels: cla-signed

#1550 Add "p" in partition names ending with digit
  buildroot-external/rootfs-overlay/usr/bin/datactl
Labels: cla-signed

#1553 Add USB stall handling for U-Boot (#1011, #1544)
  buildroot-external/board/raspberrypi/patches/uboot/0001-rpi-Use-CONFIG_OF_BOARD-instead-of-CONFIG_EMBED.patch
  buildroot-external/board/raspberrypi/patches/uboot/0002-raspberrypi-Disable-simple-framebuffer-support.patch
  buildroot-external/board/raspberrypi/patches/uboot/0003-ARM-bcm283x-change-the-virtual-address-of-the-XHCI-P.patch
  buildroot-external/board/raspberrypi/patches/uboot/0004-IOMUX-Fix-buffer-overflow-in-iomux_replace_device.patch
  buildroot-external/board/raspberrypi/patches/uboot/0005-usb-xhci-reset-endpoint-on-USB-stall.patch
Labels: cla-signed, board/raspberrypi, u-boot, REL-6

#1554 Update OS-Agent 1.2.0 & adjust datadisk support
  Documentation/partition.md
  buildroot-external/package/os-agent/os-agent.mk
  buildroot-external/rootfs-overlay/usr/bin/datactl
Labels: cla-signed, os

#1556 Bump to U-Boot 2021.10-rc5
  buildroot-external/board/asus/tinker/patches/uboot/0001-SPL-modify-load-address-of-U-Boot.patch
  buildroot-external/board/asus/tinker/patches/uboot/0002-pmic-enable-LDO2-vcc33_mipi-at-bootup.patch
  buildroot-external/board/hardkernel/patches/uboot/0001-HACK-mmc-meson-gx-limit-to-24MHz.patch
  buildroot-external/board/hardkernel/patches/uboot/0002-arm64-dts-meson-odroidc2-readd-PHY-reset-properties.patch
  buildroot-external/board/raspberrypi/patches/uboot/0001-rpi-Use-CONFIG_OF_BOARD-instead-of-CONFIG_EMBED.patch
  buildroot-external/board/raspberrypi/patches/uboot/0002-raspberrypi-Disable-simple-framebuffer-support.patch
  buildroot-external/board/raspberrypi/patches/uboot/0002-usb-xhci-reset-endpoint-on-USB-stall.patch
  buildroot-external/board/raspberrypi/patches/uboot/0003-ARM-bcm283x-change-the-virtual-address-of-the-XHCI-P.patch
  buildroot-external/board/raspberrypi/patches/uboot/0004-IOMUX-Fix-buffer-overflow-in-iomux_replace_device.patch
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/patches/uboot/2021.10-rc5/0001-CMD-read-string-from-fileinto-env.patch
Labels: cla-signed, board/raspberrypi, board/odroid, board/tinker, u-boot, board/khadas

#1557 Add NVMe boot support for RPi Compute Module 4 for U-Boot 2021.10-rc5
  buildroot-external/board/raspberrypi/kernel.config
  buildroot-external/board/raspberrypi/patches/uboot/0001-rpi-Use-CONFIG_OF_BOARD-instead-of-CONFIG_EMBED.patch
  buildroot-external/board/raspberrypi/patches/uboot/0002-usb-xhci-reset-endpoint-on-USB-stall.patch
  buildroot-external/board/raspberrypi/patches/uboot/0003-rpi-add-NVMe-to-boot-order.patch
  buildroot-external/board/raspberrypi/patches/uboot/0004-Revert-nvme-Correct-the-prps-per-page-calculation-me.patch
  buildroot-external/board/raspberrypi/patches/uboot/0005-nvme-improve-readability-of-nvme_setup_prps.patch
  buildroot-external/board/raspberrypi/patches/uboot/0006-nvme-Use-pointer-for-CPU-addressed-buffers.patch
  buildroot-external/board/raspberrypi/patches/uboot/0007-nvme-translate-virtual-addresses-into-the-bus-s-addr.patch
  buildroot-external/board/raspberrypi/rpi4-64/uboot.config
  buildroot-external/board/raspberrypi/rpi4/uboot.config
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
Labels: cla-signed, board/raspberrypi, u-boot

#1559 Bump OS Agent to 1.2.1
  buildroot-external/package/os-agent/os-agent.mk
Labels: cla-signed, os, REL-6

#1558 Make sure Intel BT gets built as a module (#820)
  buildroot-external/kernel/device-support.config
Labels: cla-signed, board/ova, REL-6, board/generic-x86-64

#1464 Support development builds in pull-requests
  .github/workflows/dev.yml
  .github/workflows/matrix.json
Labels: cla-signed, board/ova, build, run-dev-build

#1560 Bump build container to Debian bullseye
  Dockerfile
Labels: cla-signed, board/raspberrypi, board/ova, board/odroid, build, board/tinker, board/generic-x86-64, run-dev-build, board/khadas
