Repository home-assistant/operating-system, pull requests merged in 2021-05, with the labels that each got.

#1323 add ODROID-C4/N2/N2+/C2 support for RPI-RF-MOD/HM-MOD-RPI-PCB integration
  buildroot-external/board/hardkernel/kernel-amlogic.config
  buildroot-external/board/hardkernel/odroid-c2/boot-env.txt
  buildroot-external/board/hardkernel/odroid-c2/hassos-hook.sh
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/boot-env.txt
  buildroot-external/board/hardkernel/odroid-c4/hassos-hook.sh
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-n2/boot-env.txt
  buildroot-external/board/hardkernel/odroid-n2/hassos-hook.sh
  buildroot-external/board/hardkernel/odroid-n2/uboot-boot.ush
  buildroot-external/board/hardkernel/patches/linux/board-odroidc2-add-uartA-uartC.patch
  buildroot-external/board/hardkernel/patches/linux/general-meson64-i2cX-missing-pins.patch
  buildroot-external/board/hardkernel/patches/linux/hardkernel-0013-C4-arm64-dts-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/hardkernel-0021-C4-arm64-dts-add-i2c2-i2c3-node.patch
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/package/generic_raw_uart/0001-kernel-Makefile.patch
  buildroot-external/package/rpi-rf-mod/Config.in
  buildroot-external/package/rpi-rf-mod/rpi-rf-mod.mk
  buildroot-external/rootfs-overlay/etc/sysctl.d/30-cp15barrier.conf
Labels: board/odroid, cla-signed

#1352 Support OS releases with custom dev part
  .github/workflows/release.yml
Labels: build, cla-signed

#1353 Make sure to upload correct image files in release pipeline
  .github/workflows/release.yml
Labels: build, cla-signed

#1356 Fix typos in issue template
  .github/ISSUE_TEMPLATE.md
Labels: cla-signed

#1355 Update getting_started_development.md
  Documentation/getting_started_development.md
Labels: cla-signed

#1359 Fix NM connectivity URL
  buildroot-external/rootfs-overlay/etc/NetworkManager/NetworkManager.conf
Labels: REL-6, cla-signed

#1360 Delay Supervisor start until time has been sychronized
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-time-wait-sync.service.d/timeout.conf
  buildroot-external/rootfs-overlay/usr/lib/systemd/system-preset/70-haos.preset
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/hassos-supervisor.service
Labels: cla-signed, os

#1364 Linux: Update kernel 5.10.37
  Documentation/kernel.md
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: board/generic-x86-64, board/odroid, board/ova, board/tinker, cla-signed

#1365 RaspberryPi: Update kernel 5.10.17 - raspberrypi-kernel_1.20210430-1
  Documentation/kernel.md
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
Labels: board/raspberrypi, cla-signed

#1366 Start Home Assistant CLI on tty1 without login
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/rootfs-overlay/etc/systemd/system/getty@.service.d/hassos.conf
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/ha-cli@.service
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/ha-cli@.service.d/haos.conf
  buildroot-external/rootfs-overlay/usr/sbin/hassos-cli
  buildroot-external/scripts/post-build.sh
  buildroot-external/scripts/rootfs-layer.sh
Labels: cla-signed, os

#1369 Remove obsolete Busybox ACPI config
  buildroot-external/rootfs-overlay/etc/acpi/PWRF/00000080
Labels: cla-signed, os

#1368 Recreate Supervisor container on OS upgrade/downgrade
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed, os-update

#1373 Add minimal message of the day
  buildroot-external/rootfs-overlay/etc/motd
Labels: cla-signed, os

#1372 Drop directories when creating zip file
  buildroot-external/scripts/hdd-image.sh
Labels: board/ova, cla-signed

#1377 Pass ha command with quotes to CLI container
  buildroot-external/rootfs-overlay/usr/bin/ha
Labels: cla-signed, os

#1378 Enable serial console as well (#1339)
  buildroot-external/board/pc/ova/hassos-hook.sh
Labels: board/ova, cla-signed

#1379 Revert ODROID-N2(+) back to use Linux 5.9
  buildroot-external/board/hardkernel/patches/linux/0001-arm64-dts-meson-convert-ODROID-N2-to-dtsi.patch
  buildroot-external/board/hardkernel/patches/linux/0002-dt-bindings-arm-amlogic-add-support-for-the-ODROID-N.patch
  buildroot-external/board/hardkernel/patches/linux/0003-arm64-dts-meson-add-support-for-the-ODROID-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0004-arm64-dts-meson-add-i2c3-rtc-nodes-and-rtc-aliases-t.patch
  buildroot-external/board/hardkernel/patches/linux/0005-arm64-dts-meson-add-saradc-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0006-arm64-dts-meson-add-GPIO-line-names-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0007-arm64-dts-meson-g12b-add-power-button-support.patch
  buildroot-external/board/hardkernel/patches/linux/0008-arm64-dts-meson-g12b-add-GPIO-fan-support.patch
  buildroot-external/board/hardkernel/patches/linux/0009-arm64-dts-meson-g12b-odroid-n2-add-fan-as-cooling-de.patch
  buildroot-external/board/hardkernel/patches/linux/0010-arm64-dts-meson-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/0011-arm64-dts-meson-add-i2c2-node-to-ODROID-N2-N2.patch
  buildroot-external/configs/odroid_n2_defconfig
Labels: board/odroid, cla-signed

#1380 Update Barebox to 2021.05.0
  buildroot-external/board/pc/barebox.config
  buildroot-external/bootloader/barebox.config
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/ova_defconfig
Labels: board/generic-x86-64, board/ova, cla-signed

#1381 Keep Linux patches for 5.10.37 for other ODROID boards
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0001-arm64-dts-meson-add-i2c3-rtc-nodes-and-rtc-aliases-t.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0002-arm64-dts-meson-add-saradc-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0003-arm64-dts-meson-add-GPIO-line-names-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0004-arm64-dts-meson-g12b-add-power-button-support.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0005-arm64-dts-meson-g12b-add-GPIO-fan-support.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0006-arm64-dts-meson-g12b-odroid-n2-add-fan-as-cooling-de.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0007-arm64-dts-meson-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0008-arm64-dts-meson-add-i2c2-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0001-arm64-dts-meson-convert-ODROID-N2-to-dtsi.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0002-dt-bindings-arm-amlogic-add-support-for-the-ODROID-N.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0003-arm64-dts-meson-add-support-for-the-ODROID-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0004-arm64-dts-meson-add-i2c3-rtc-nodes-and-rtc-aliases-t.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0005-arm64-dts-meson-add-saradc-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0006-arm64-dts-meson-add-GPIO-line-names-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0007-arm64-dts-meson-g12b-add-power-button-support.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0008-arm64-dts-meson-g12b-add-GPIO-fan-support.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0009-arm64-dts-meson-g12b-odroid-n2-add-fan-as-cooling-de.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0010-arm64-dts-meson-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0011-arm64-dts-meson-add-i2c2-node-to-ODROID-N2-N2.patch
Labels: board/odroid, cla-signed

#1382 Add additional directories to .dockerignore
  .dockerignore
Labels: cla-signed
