Repository home-assistant/operating-system, pull requests merged in 2021-08, with the labels that each got.

#1495 teeny typo
  Documentation/boards/README.md
Labels: cla-signed

#1496 Fix Ralink RT73 package selection (#1443)
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, os, REL-6

#1473 Add Khadas VIM3
  buildroot-external/Config.in
  buildroot-external/board/khadas/kernel-vim.config
  buildroot-external/board/khadas/vim3/boot-env.txt
  buildroot-external/board/khadas/vim3/hassos-hook.sh
  buildroot-external/board/khadas/vim3/meta
  buildroot-external/board/khadas/vim3/uboot-boot.ush
  buildroot-external/board/khadas/vim3/uboot.config
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/package/khadas-boot/Config.in
  buildroot-external/package/khadas-boot/khadas-boot.mk
Labels: cla-signed

#1497 Enable HDMI CEC drivers for ODROID-N2 (#1216)
  buildroot-external/board/hardkernel/kernel-amlogic.config
Labels: cla-signed, board/odroid, REL-6

#1498 Add Khadas VIM3 to GitHub Actions
  .github/ISSUE_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/dev.yml
  .github/workflows/release.yml
Labels: cla-signed, board/khadas

#1509 Add support for Keyspan USB-Serial adapters
  buildroot-external/kernel/device-support.config
Labels: cla-signed, REL-6
