Repository home-assistant/operating-system, pull requests merged in 2021-02, with the labels that each got.

#1205 Bump systemd to latest stable release 246.10
  buildroot-patches/0001-docker-add-AppArmor-support.patch
  buildroot-patches/0002-rpi-firmware-Bump-firmware.patch
  buildroot-patches/0003-network-manager-wpa_supplicant.patch
  buildroot-patches/0004-Fix-dhcp-client.patch
  buildroot-patches/0005-rpi-use-latest-wifi-driver.patch
  buildroot-patches/0006-package-linux-firmware-add-new-option-for-Samsung-MF.patch
  buildroot-patches/0007-docker-proxy-Bump-version.patch
  buildroot-patches/0008-systemd-Bump-to-latest-systemd-stable-release-246.10.patch
  buildroot-patches/0009-package-linux-firmware-add-new-option-for-USB-TI-341.patch
  buildroot/package/systemd/systemd.hash
  buildroot/package/systemd/systemd.mk
Labels: REL-5, cla-signed, os

#1204 Fix partition resize for MBR for all sizes (#1193)
  buildroot-external/rootfs-overlay/usr/libexec/hassos-expand
Labels: REL-5, board/odroid, cla-signed, os

#1211 RaspberryPi: Update firmware 0d458874a89921fbe460e422b239695e1e101e2b
  buildroot-patches/0002-rpi-firmware-Bump-firmware.patch
  buildroot/package/rpi-firmware/rpi-firmware.hash
  buildroot/package/rpi-firmware/rpi-firmware.mk
  scripts/update-firmware-rpi.sh
Labels: REL-5, board/raspberrypi, cla-signed

#1210 Disable acpid
  buildroot-external/busybox.config
Labels: cla-signed

#1214 Bump kernel to 5.10 LTS
  Documentation/kernel.md
  buildroot-external/board/asus/tinker/patches/linux/1011-ARM-DTSI-rk3288-Adding-missing-VOPB-registers.patch
  buildroot-external/board/asus/tinker/patches/linux/1015-ARM-DTSI-rk3288-tinker-Improving-the-CPU-max-voltage.patch
  buildroot-external/board/asus/tinker/patches/linux/1016-ARM-DTSI-rk3288-tinker-Setting-up-the-SD-regulators.patch
  buildroot-external/board/asus/tinker/patches/linux/2009-drm-dw_hdmi-rockchip-better-clock-selection-logic-an.patch
  buildroot-external/board/hardkernel/patches/linux/0001-arm64-dts-meson-add-RTC-to-ODROID-N2-boards.patch
  buildroot-external/board/hardkernel/patches/linux/0001-arm64-dts-meson-convert-ODROID-N2-to-dtsi.patch
  buildroot-external/board/hardkernel/patches/linux/0002-arm64-dts-meson-g12b-add-power-button-support.patch
  buildroot-external/board/hardkernel/patches/linux/0002-dt-bindings-arm-amlogic-add-support-for-the-ODROID-N.patch
  buildroot-external/board/hardkernel/patches/linux/0003-arm64-dts-meson-add-support-for-the-ODROID-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0003-arm64-dts-meson-g12b-add-GPIO-fan-support.patch
  buildroot-external/board/hardkernel/patches/linux/0004-arm64-dts-meson-g12b-odroid-n2-add-fan-as-cooling-de.patch
  buildroot-external/board/hardkernel/patches/linux/0004-arm64-dts-meson-odroid-n2-plus-fix-vddcpu_a-pwm.patch
  buildroot-external/board/hardkernel/patches/linux/0006-arm64-dts-meson-g12b-odroid-n2-fix-PHY-deassert-timi.patch
  buildroot-external/board/hardkernel/patches/linux/0007-arm64-dts-meson-fix-PHY-deassert-timing-requirements.patch
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
  scripts/update-kernel-odroid.sh
  scripts/update-kernel-upstream.sh
Labels: board/intel-nuc, board/odroid, board/ova, board/tinker, cla-signed

#1215 Bump out-of-tree Intel e1000e driver to build with Linux 5.10
  buildroot-external/package/intel-e1000e/intel-e1000e.hash
  buildroot-external/package/intel-e1000e/intel-e1000e.mk
Labels: cla-signed

#1219 Deploy all variants of the Raspberry Pi firmwares (#947)
  buildroot-external/board/raspberrypi/hassos-hook.sh
  buildroot-external/package/rpi-firmware/rpi-firmware.mk
Labels: board/raspberrypi, cla-signed

#1222 Increase maximum IGMP memberships
  buildroot-external/rootfs-overlay/etc/sysctl.d/20-network.conf
Labels: cla-signed

#1228 Add SocketCAN support
  buildroot-external/kernel/device-support.config
Labels: cla-signed

#1230 Linux: Update kernel 5.4.99
  Documentation/kernel.md
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: REL-5, board/intel-nuc, board/ova, board/tinker, cla-signed

#1231 Linux: Update kernel 5.10.17
  Documentation/kernel.md
  buildroot-external/configs/intel_nuc_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: board/intel-nuc, board/odroid, board/ova, board/tinker, cla-signed

#1234 Fix Bluetooth on ASUS Tinker
  buildroot-external/board/asus/tinker/patches/linux/0001-Revert-ARM-dts-rockchip-use-DMA-channels-for-UARTs-f.patch
  buildroot-external/board/asus/tinker/patches/linux/1010-ARM-DTSI-rk3288-Adding-missing-EDP-power-domain.patch
  buildroot-external/board/asus/tinker/patches/linux/1012-ARM-DTSI-rk3288-Fixed-the-SPDIF-node-address.patch
  buildroot-external/board/asus/tinker/patches/linux/1013-ARM-DTS-rk3288-tinker-Enabling-SDIO-and-Wifi.patch
  buildroot-external/board/asus/tinker/patches/linux/1015-ARM-DTSI-rk3288-tinker-Improving-the-CPU-max-voltage.patch
  buildroot-external/board/asus/tinker/patches/linux/1019-ARM-DTSI-rk3288-tinker-Defining-SDMMC-properties.patch
  buildroot-external/board/asus/tinker/patches/linux/1020-ARM-DTSI-rk3288-Set-the-VPU-MMU-power-domains.patch
  buildroot-external/board/asus/tinker/patches/linux/1023-dts-rk3288-support-for-dedicating-npll-to-a-vop.patch
  buildroot-external/board/asus/tinker/patches/linux/2002-clk-rockchip-add-all-known-operating-points-to-the-a.patch
  buildroot-external/board/asus/tinker/patches/linux/2006-soc-rockchip-power-domain-export-idle-request.patch
  buildroot-external/board/asus/tinker/patches/linux/2007-drivers-wifi-ath9k-reverse-do-not-use-bulk-on-EP3-and-EP4.patch
  buildroot-external/board/asus/tinker/patches/linux/2008-clk-rockchip-rk3288-Support-for-dedicating-NPLL-to-a.patch
  buildroot-external/board/asus/tinker/patches/linux/2013-spi-Added-support-for-Tinkerboard-s-SPI-interface.patch
  buildroot-external/board/asus/tinker/patches/linux/261_gpiomem_driver.patch
  buildroot-external/board/asus/tinker/patches/linux/3000_DTS_rearrange_thermal_zones.patch
  buildroot-external/board/asus/tinker/patches/linux/RK3288-1.8GHz-and-boost.patch
  buildroot-external/board/asus/tinker/patches/linux/brcmfmac-add-ap6330-firmware.patch
  buildroot-external/board/asus/tinker/patches/linux/general-adjust-tinker-dts-hdmi-sound.patch
  buildroot-external/board/asus/tinker/patches/linux/general-fix-reboot-from-kwiboo.patch
  buildroot-external/board/asus/tinker/patches/linux/remove-broken-dtb.patch
  buildroot-external/package/bluetooth-rtl8723/bluetooth-rtl8723
Labels: board/tinker, cla-signed

#1246 Don't filter previous releases on dev branch
  .github/release-drafter.yml
Labels: cla-signed

#1236 Add --cpu-rt-runtime to allow Docker allocate real-time CPU time (#1235)
  buildroot-external/rootfs-overlay/etc/systemd/system/docker.service.d/hassos.conf
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed

#1233 Update ovf:id to get Synology VMM detect Guest Agent
  buildroot-external/board/intel/ova/home-assistant.ovf
Labels: board/ova, cla-signed
