Repository home-assistant/operating-system, pull requests merged in 2021-07, with the labels that each got.

#1444 Dockerfile: Add dependencies for make graph-depends/-size targets
  Dockerfile
Labels: build, cla-signed

#1437 Using image name from version file
  buildroot-external/package/hassio/builder/hostapp.sh
Labels: REL-6, cla-signed

#1451 Supoport compressed squashfs for kernel (#1418)
  buildroot-external/board/asus/tinker/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-n2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot64.ush
  buildroot-external/bootloader/barebox.config
  buildroot-external/bootloader/barebox/boot/system0
  buildroot-external/bootloader/barebox/boot/system1
  buildroot-external/bootloader/uboot.config
  buildroot-external/scripts/rauc.sh
Labels: REL-6, cla-signed, os-update

#1452 Drop superseeded CRDA utility
  buildroot-external/board/asus/tinker/kernel.config
  buildroot-external/board/hardkernel/kernel-amlogic.config
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os

#1453 Ignore build output directory
  .dockerignore
  .gitignore
Labels: build, cla-signed

#1454 Use sparse file for pre-composed data partition
  buildroot-external/package/hassio/builder/hostapp.sh
Labels: cla-signed, os

#1456 RaspberryPi: Update kernel 5.10.17 - 1.20210527-1 (#1450)
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
Labels: REL-6, board/raspberrypi, cla-signed

#1461 Remove original images when creating zip
  buildroot-external/scripts/hdd-image.sh
Labels: REL-6, build, cla-signed

#1462 Avoid using tar when uploading dev builds
  .github/workflows/dev.yml
Labels: build, cla-signed

#1459 Improve Xen support
  .github/workflows/pr-checks.yml
  buildroot-external/Config.in
  buildroot-external/board/pc/ova/kernel.config
  buildroot-external/configs/ova_defconfig
  buildroot-external/package/xe-guest-utilities/Config.in
  buildroot-external/package/xe-guest-utilities/proc-xen.mount
  buildroot-external/package/xe-guest-utilities/tmpfile.conf
  buildroot-external/package/xe-guest-utilities/xe-daemon.service
  buildroot-external/package/xe-guest-utilities/xe-guest-utilities.mk
  buildroot-external/package/xe-guest-utilities/xe-linux-distribution
Labels: board/ova, cla-signed

#1475 Bump to Linux 5.10.53
  Documentation/kernel.md
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0001-arm64-dts-meson-add-i2c3-rtc-nodes-and-rtc-aliases-t.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0002-arm64-dts-meson-add-saradc-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0003-arm64-dts-meson-add-GPIO-line-names-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0004-arm64-dts-meson-g12b-add-power-button-support.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0005-arm64-dts-meson-g12b-add-GPIO-fan-support.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0006-arm64-dts-meson-g12b-odroid-n2-add-fan-as-cooling-de.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0007-arm64-dts-meson-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0008-arm64-dts-meson-add-i2c2-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0009-ODROID-XU4-Update-hack-avoiding-the-invalid-temperat.patch
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
  scripts/update-kernel-odroid-n2.sh
  scripts/update-kernel-upstream.sh
Labels: REL-6, board/generic-x86-64, board/intel-nuc, board/odroid, board/ova, board/tinker, cla-signed

#1476 board: hardkernel: Fix random crash on Linux kernel 5.10 and newer
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0009-Revert-of-fdt-Make-sure-no-map-does-not-remove-alrea.patch
Labels: REL-6, board/odroid, cla-signed

#1477 Remove duplicated patch file
  buildroot-external/board/hardkernel/patches/linux/5.10.53/0009-ODROID-XU4-Update-hack-avoiding-the-invalid-temperat.patch
Labels: board/odroid, cla-signed

#1479 Enable support for Ralink rt27xx/rt28xx/rt30xx and rt73 devices (#1443)
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/kernel/device-support.config
Labels: REL-6, cla-signed

#1480 Add firmware for Realtek 87xx/88xx Bluetooth devices (#1427)
  buildroot-external/configs/rpi0_w_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/kernel/device-support.config
Labels: REL-6, board/raspberrypi, cla-signed

#1481 buildroot: package/lvm2: install dmsetup only (#1448)
  buildroot-patches/0001-docker-add-AppArmor-support.patch
  buildroot-patches/0002-network-manager-wpa_supplicant.patch
  buildroot-patches/0003-Fix-dhcp-client.patch
  buildroot-patches/0004-package-rpi-firmware-Allow-to-deploy-multiple-firmwa.patch
  buildroot-patches/0005-package-linux-firmware-add-RTL87XX-RTL88XX-Bluetooth.patch
  buildroot-patches/0006-package-docker-proxy-bump-version-to-b3507428be5b.patch
  buildroot-patches/0007-package-rpi-firmware-bump-version-to-1.20210303.patch
  buildroot-patches/0008-package-linux-firmware-add-rtl8761b-rtl8761bu-firmwa.patch
  buildroot-patches/0009-package-lvm2-fix-installation-of-systemd-units.patch
  buildroot/package/lvm2/lvm2.mk
Labels: REL-6, cla-signed

#1484 Add Bluetooth firmware file for Raspberry Pi 400 (#1469)
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.mk
Labels: REL-6, board/raspberrypi, cla-signed

#1485 buildroot: package/rpi-wifi-firmware: bump version to 883b726
  buildroot-patches/0001-docker-add-AppArmor-support.patch
  buildroot-patches/0002-network-manager-wpa_supplicant.patch
  buildroot-patches/0003-Fix-dhcp-client.patch
  buildroot-patches/0004-package-rpi-firmware-Allow-to-deploy-multiple-firmwa.patch
  buildroot-patches/0005-package-linux-firmware-add-RTL87XX-RTL88XX-Bluetooth.patch
  buildroot-patches/0006-package-docker-proxy-bump-version-to-b3507428be5b.patch
  buildroot-patches/0007-package-rpi-firmware-bump-version-to-1.20210303.patch
  buildroot-patches/0008-package-linux-firmware-add-rtl8761b-rtl8761bu-firmwa.patch
  buildroot-patches/0009-package-lvm2-fix-installation-of-systemd-units.patch
  buildroot-patches/0010-package-rpi-wifi-firmware-bump-version-to-883b726.patch
  buildroot/package/rpi-wifi-firmware/rpi-wifi-firmware.hash
  buildroot/package/rpi-wifi-firmware/rpi-wifi-firmware.mk
Labels: cla-signed
