Repository home-assistant/operating-system, pull requests merged in 2021-12, with the labels that each got.

#1653 Updated to latest generic_raw_uart package
  buildroot-external/package/generic_raw_uart/generic_raw_uart.hash
  buildroot-external/package/generic_raw_uart/generic_raw_uart.mk
Labels: cla-signed, REL-7

#1658 Linux: Update kernel 5.10.83
  Documentation/kernel.md
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, REL-7

#1668 Update download URL for package intel-e1000e
  buildroot-external/package/intel-e1000e/intel-e1000e.mk
Labels: cla-signed

#1669 rtl8812au: use buildroot provided aircrack-ng driver (#1660)
  buildroot-external/Config.in
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/package/rtl8812au/Config.in
  buildroot-external/package/rtl8812au/rtl8812au.mk
Labels: cla-signed, board/odroid, board/khadas

#1671 Avoid race condition when fetching containers during build
  buildroot-external/package/hassio/fetch-container-image.sh
Labels: cla-signed, build, REL-7

#1676 Re-upload rebuilt files
  .github/workflows/dev.yml
Labels: cla-signed, build

#1674 Adjust ova to support VMware ESXi (#826)
  buildroot-external/board/pc/ova/hassos-hook.sh
  buildroot-external/board/pc/ova/home-assistant.ovf
Labels: cla-signed, board/ova, run-dev-build, REL-7

#1684 Devices description update
  Documentation/boards/README.md
  Documentation/boards/raspberrypi/README.md
  README.md
Labels: cla-signed

#1693 Linux: Update kernel 5.10.88
  Documentation/kernel.md
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, kernel, board/odroid, board/tinker, board/generic-x86-64, board/khadas

#1694 Check if Busybox supports oflag (#1692)
  buildroot-external/ota/rauc-hook
Labels: cla-signed, os, os-update

#1695 Use LSI Logic SCSI controller
  buildroot-external/board/pc/ova/hassos-hook.sh
  buildroot-external/scripts/hdd-image.sh
Labels: cla-signed, board/ova

#1699 ODROID XU4: Update U-Boot on eMMC boot partition
  buildroot-external/ota/rauc-hook
Labels: cla-signed, board/odroid, os-update, REL-6
