Repository home-assistant/operating-system, pull requests merged in 2021-06, with the labels that each got.

#1386 Avoid spurious shutdown on ODROID-XU4 (#1385)
  buildroot-external/board/hardkernel/odroid-xu4/patches/linux/0001-ODROID-XU4-Update-hack-avoiding-the-invalid-temperat.patch
  buildroot-external/configs/odroid_xu4_defconfig
Labels: board/odroid, cla-signed

#1388 Enhancement: add thinkpad_acpi module
  buildroot-external/board/pc/generic-x86-64/kernel.config
Labels: board/generic-x86-64, cla-signed

#1391 Restart console on tty1 on exit (#1387)
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/ha-cli@.service
Labels: cla-signed, os

#1393 Verify Power Supply Size
  Documentation/partition.md
Labels: cla-signed

#1395 Bump linux to 5.10.42
  Documentation/kernel.md
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: board/generic-x86-64, board/odroid, board/ova, board/tinker, cla-signed, linux

#1404 Bump OS release version to 7
  buildroot-external/meta
Labels: cla-signed, os

#1400 pc/ova: support virtio-fs
  buildroot-external/board/pc/ova/kernel.config
Labels: board/ova, cla-signed

#1406 Use file system extents for the kernel partition
  buildroot-external/scripts/hdd-image.sh
Labels: cla-signed, os

#1408 Use direct I/O for SPL update
  buildroot-external/ota/rauc-hook
Labels: cla-signed, os-update

#1412 Remove unnecessary ODROID-N2 kernel patches
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0001-arm64-dts-meson-add-i2c3-rtc-nodes-and-rtc-aliases-t.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0002-arm64-dts-meson-add-saradc-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0003-arm64-dts-meson-add-GPIO-line-names-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0004-arm64-dts-meson-g12b-add-power-button-support.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0005-arm64-dts-meson-g12b-add-GPIO-fan-support.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0006-arm64-dts-meson-g12b-odroid-n2-add-fan-as-cooling-de.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0007-arm64-dts-meson-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.37/0008-arm64-dts-meson-add-i2c2-node-to-ODROID-N2-N2.patch
Labels: REL-6, board/odroid, cla-signed

#1405 Set deployment type to production (#1404)
  buildroot-external/meta
Labels: REL-6, cla-signed, os

#1414 Bump ODROID-N2 to Linux 5.12
  buildroot-external/board/hardkernel/patches/linux/5.12.10/0001-arm64-dts-meson-add-saradc-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.12.10/0002-arm64-dts-meson-add-GPIO-line-names-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.12.10/0003-arm64-dts-meson-g12b-add-power-button-support.patch
  buildroot-external/board/hardkernel/patches/linux/5.12.10/0004-arm64-dts-meson-g12b-add-GPIO-fan-support.patch
  buildroot-external/board/hardkernel/patches/linux/5.12.10/0005-arm64-dts-meson-g12b-odroid-n2-add-fan-as-cooling-de.patch
  buildroot-external/board/hardkernel/patches/linux/5.12.10/0006-arm64-dts-meson-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/5.12.10/0007-arm64-dts-meson-add-i2c2-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0001-arm64-dts-meson-convert-ODROID-N2-to-dtsi.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0002-dt-bindings-arm-amlogic-add-support-for-the-ODROID-N.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0003-arm64-dts-meson-add-support-for-the-ODROID-N2.patch
  buildroot-external/board/hardkernel/patches/linux/5.9.16/0004-arm64-dts-meson-add-i2c3-rtc-nodes-and-rtc-aliases-t.patch
  buildroot-external/configs/odroid_n2_defconfig
Labels: board/odroid, cla-signed, linux

#1415 Move ODROID patches
  buildroot-external/board/hardkernel/patches/linux/5.10.42/board-odroidc2-add-uartA-uartC.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.42/general-meson64-i2cX-missing-pins.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.42/hardkernel-0013-C4-arm64-dts-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.42/hardkernel-0021-C4-arm64-dts-add-i2c2-i2c3-node.patch
Labels: board/odroid, cla-signed

#1416 rtl8812au: bump to latest aircrack-ng 5.7.0 version
  buildroot-external/package/rtl8812au/rtl8812au.mk
Labels: cla-signed, os

#1417 Update generic_raw_uart package to latest version
  buildroot-external/package/generic_raw_uart/generic_raw_uart.mk
Labels: REL-6, cla-signed, os-update

#1418 Use compressed squashfs for kernel
  buildroot-external/board/asus/tinker/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-n2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot64.ush
  buildroot-external/bootloader/barebox.config
  buildroot-external/bootloader/barebox/boot/system0
  buildroot-external/bootloader/barebox/boot/system1
  buildroot-external/bootloader/uboot.config
  buildroot-external/scripts/hdd-image.sh
  buildroot-external/scripts/name.sh
  buildroot-external/scripts/ota.sh
  buildroot-external/scripts/rauc.sh
Labels: cla-signed

#1424 Linux: Update kernel 5.10.45
  Documentation/kernel.md
  buildroot-external/board/hardkernel/patches/linux/5.10.45/board-odroidc2-add-uartA-uartC.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.45/general-meson64-i2cX-missing-pins.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.45/hardkernel-0013-C4-arm64-dts-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/5.10.45/hardkernel-0021-C4-arm64-dts-add-i2c2-i2c3-node.patch
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: REL-6, board/generic-x86-64, board/odroid, board/ova, board/tinker, cla-signed, linux

#1423 Add firmware for RTL8761B/BU devices (#1392)
  buildroot-patches/0001-docker-add-AppArmor-support.patch
  buildroot-patches/0002-network-manager-wpa_supplicant.patch
  buildroot-patches/0003-Fix-dhcp-client.patch
  buildroot-patches/0004-package-rpi-firmware-Allow-to-deploy-multiple-firmwa.patch
  buildroot-patches/0005-package-linux-firmware-add-RTL87XX-RTL88XX-Bluetooth.patch
  buildroot-patches/0006-package-docker-proxy-bump-version-to-b3507428be5b.patch
  buildroot-patches/0007-package-rpi-firmware-bump-version-to-1.20210303.patch
  buildroot-patches/0008-package-linux-firmware-add-rtl8761b-rtl8761bu-firmwa.patch
  buildroot/package/linux-firmware/linux-firmware.hash
  buildroot/package/linux-firmware/linux-firmware.mk
Labels: REL-6, cla-signed, os

#1429 Adjust recommended platforms
  Documentation/boards/README.md
Labels: cla-signed

#1430 Update generic_raw_uart module to latest version
  buildroot-external/package/generic_raw_uart/generic_raw_uart.mk
Labels: cla-signed
