Repository home-assistant/operating-system, pull requests merged in 2022-09, with the labels that each got.

#2102 Add access to containerd for Supervisor
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed, os

#2103 Bump commit interval to 30s
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/mnt-data.mount
Labels: cla-signed, os

#2107 Remove dev from release drafter
  .github/workflows/release-drafter.yml
Labels: cla-signed, build

#2106 Enable dependencies for IPv6 NAT support
  buildroot-external/kernel/docker.config
Labels: cla-signed, os, linux

#2108 ODROID-XU4: Reset Ethernet properly on reboot (#1488)
  buildroot-external/board/hardkernel/odroid-xu4/patches/linux/0001-ODROID-XU4-regulator-s2mps11-add-ethernet-power-rese.patch
Labels: cla-signed, board/odroid

#2112 Try booting up to 3 times on GRUB2 based systems
  buildroot-external/board/arm-uefi/generic-aarch64/grub.cfg
  buildroot-external/board/pc/grub.cfg
Labels: cla-signed, board/ova, board/generic-x86-64, board/generic-aarch64, grub2, REL-9

#2113 Try using old image name of the Supervisor image (#2111)
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed, os, REL-9

#2114 Linux: Update kernel 5.15.65
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, REL-9

#2116 Move Docker configuration to daemon.json
  buildroot-external/rootfs-overlay/etc/docker/daemon.json
  buildroot-external/rootfs-overlay/etc/systemd/system/docker.service.d/hassos.conf
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/etc-docker.mount
Labels: cla-signed, os

#2118 Remove image name from journald tag/identifier
  buildroot-external/rootfs-overlay/etc/docker/daemon.json
Labels: cla-signed, os, REL-9

#2123 Add Qualcomm QCA6174/QCA6174A Bluetooth/WiFi support (#2122)
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/ova_defconfig
Labels: cla-signed, board/ova, board/generic-x86-64, board/generic-aarch64, REL-9

#2124 Drop unused cgroup_enable=memory kernel parameter
  buildroot-external/board/arm-uefi/generic-aarch64/grub.cfg
  buildroot-external/board/asus/tinker/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-n2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
  buildroot-external/board/khadas/vim3/uboot-boot.ush
  buildroot-external/board/pc/grub.cfg
Labels: cla-signed, os, linux, REL-9

#2125 Fix Docker key.json corruption check
  buildroot-external/rootfs-overlay/usr/libexec/docker-failure
Labels: cla-signed, os, REL-9

#2126 Linux: Update kernel 5.15.67
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas, board/generic-aarch64

#2127 Connectivity check interval to 10 minutes
  buildroot-external/rootfs-overlay/etc/NetworkManager/NetworkManager.conf
Labels: cla-signed, os

#2128 Backport patch to fix ODROID-N2 HDMI
  buildroot-external/board/hardkernel/patches/linux/0001-arm64-dts-meson-g12b-add-power-button-support.patch
  buildroot-external/board/hardkernel/patches/linux/0002-arm64-dts-meson-g12b-add-GPIO-fan-support.patch
  buildroot-external/board/hardkernel/patches/linux/0003-arm64-dts-meson-g12b-odroid-n2-add-fan-as-cooling-de.patch
  buildroot-external/board/hardkernel/patches/linux/0004-arm64-dts-meson-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/0005-arm64-dts-meson-add-i2c2-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0006-ODROID-C4-arm64-dts-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/0007-ODROID-C4-arm64-dts-add-i2c2-i2c3-node.patch
  buildroot-external/board/hardkernel/patches/linux/0008-drm-bridge-display-connector-implement-bus-fmts-call.patch
Labels: cla-signed, board/odroid

#2131 Remove UI reference from configuration USB flash drive docs (#2129)
  Documentation/configuration.md
Labels: cla-signed

#2138 Fix proxmox mem hotplug, improve virtual hw support
  buildroot-external/board/pc/ova/kernel.config
Labels: cla-signed

#2146 Linux: Update kernel 5.15.68
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas, board/generic-aarch64, REL-9

#2149 Enable .config via /proc/config.gz + zcat via busybox
  buildroot-external/busybox.config
  buildroot-external/kernel/hassos.config
Labels: cla-signed

#2150 Linux: Update kernel 5.15.69
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas, board/generic-aarch64, REL-9

#2152 Add comments, ignore vscode*
  .gitignore
Labels: cla-signed

#2157 Add OS-Agent 1.4.1 support
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/configs/yellow_defconfig
  buildroot-external/package/os-agent/Config.in
  buildroot-external/package/os-agent/os-agent.mk
Labels: cla-signed, os

#2160 Allow multicast forwarding for IPv4
  buildroot-external/kernel/hassos.config
Labels: cla-signed, board/ova, run-dev-build, REL-9
