Repository home-assistant/operating-system, pull requests merged in 2022-08, with the labels that each got.

#2036 Check if GRUB environment is valid (#2031)
  buildroot-external/ota/rauc-hook
Labels: board/ova, os-update, board/generic-x86-64, board/generic-aarch64, grub2

#2038 Add LED control through device tree overrides
  buildroot-external/board/raspberrypi/yellow/patches/linux/0001-ARM-dts-bcm2711-Add-device-tree-for-Home-Assistant-Y.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0002-ARM-dts-bcm2711-yellow-Mux-UART4-for-SiLabs-radio-mo.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0003-ARM-dts-bcm2711-yellow-Mux-debug-UART5.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0004-ARM-dts-bcm2711-yellow-Enable-I2C6-by-default.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0005-ARM-dts-bcm2711-yellow-add-I2S-audio-codec.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0006-ARM-dts-bcm2711-yellow-enable-GPIO-keys.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0007-ARM-dts-bcm2711-yellow-add-user-LED.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0008-ARM-dts-bcm2711-yellow-add-NXP-PCF85063A-RTC.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0009-ARM-dts-bcm2711-yellow-enable-USB-host-mode-by-defau.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0010-ARM-dts-bcm2711-yellow-use-generic-activity-trigger-.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0011-ARM-dts-bcm2711-yellow-use-USB-OTG-mode-by-default.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0012-gpio-raspberrypi-exp-Workaround-polarity-firmware-bu.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0013-ARM-dts-bcm2711-yellow-Add-LED-overrides.patch
Labels: cla-signed, board/yellow

#2043 Linux: Update kernel 5.15.59
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas, board/generic-aarch64

#2047 Enable USB/IP kernel modules
  buildroot-external/kernel/device-support.config
Labels: cla-signed, os

#2050 Set lower OOM Score for Supervisor
  buildroot-external/rootfs-overlay/etc/systemd/system/docker.service.d/hassos.conf
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed

#2054 Load container images desceding by size
  buildroot-external/package/hassio/dind-import-containers.sh
Labels: cla-signed, build

#2057 Synchronize network time quicker on bootup
  buildroot-external/rootfs-overlay/etc/systemd/timesyncd.conf
Labels: cla-signed, os, REL-8

#2051 Support IPv6 NAT
  buildroot-external/kernel/docker.config
  buildroot-external/rootfs-overlay/etc/systemd/system/docker.service.d/hassos.conf
Labels: cla-signed, board/ova, run-dev-build

#2058 Linux: Update kernel 5.15.60
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas, board/generic-aarch64

#2061 Remove duplicate ASMedia quirk 174c:55aa:u
  buildroot-external/board/raspberrypi/cmdline.txt
Labels: cla-signed

#2065 Enable BlueZ Audio and HID plug-ins (#2064, #1746)
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/configs/yellow_defconfig
Labels: cla-signed, os

#2067 Kernel config tweaks for Bluetooth and OverlayFS
  buildroot-external/kernel/device-support.config
  buildroot-external/kernel/docker.config
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os

#2068 Delay systemd-timesyncd start after network is deemed online
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-time-wait-sync.service.d/network-online.conf
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-timesyncd.service.d/hassos.conf
Labels: cla-signed, os

#2069 Fix delaying systemd-timesyncd start
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-time-wait-sync.service.d/network-online.conf
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-timesyncd.service.d/hassos.conf
Labels: cla-signed, os

#2070 Linux: Update kernel 5.15.61
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas, board/generic-aarch64

#2082 Fix delaying systemd-timesyncd start correctly
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-timesyncd.service
  buildroot-external/rootfs-overlay/etc/systemd/system/systemd-timesyncd.service.d/hassos.conf
Labels: cla-signed, os

#2083 Start dropbear SSH server earlier
  buildroot-external/rootfs-overlay/etc/systemd/system/dropbear.service.d/docker.conf
Labels: cla-signed, os

#2084 Linux: Update kernel 5.15.62
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas, board/generic-aarch64

#2093 Linux: Update kernel 5.15.63
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed

#2094 Enable k10temp kernel module
  buildroot-external/board/pc/generic-x86-64/kernel.config
Labels: board/generic-x86-64

#2073 rpi4: Enable arm_boost=1 to unlock 1.8Ghz CPU
  buildroot-external/board/raspberrypi/config.txt
Labels: cla-signed

#2096 Add GRUB2 boot entry to boot into rescue shell
  buildroot-external/board/pc/grub.cfg
Labels: cla-signed, board/ova, board/generic-x86-64, board/generic-aarch64

#2097 Check free disk space before starting Docker (#2092)
  buildroot-external/rootfs-overlay/etc/systemd/system/docker.service.d/failure.conf
  buildroot-external/rootfs-overlay/usr/libexec/docker-disk-check
Labels: cla-signed, os

#2101 Do not send excessive DNS queries for online checks (#2100)
  buildroot-external/patches/network-manager/0001-connectivity-handle-NoNameServers-resolved-error-and.patch
Labels: cla-signed, os
