Repository home-assistant/operating-system, pull requests merged in 2022-07, with the labels that each got.

#1992 Using Yellow for HA images (landingpage)
  buildroot-external/board/raspberrypi/yellow/meta
Labels: cla-signed, REL-8

#2002 Linux: Update kernel 5.15.52
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/yellow, board/generic-aarch64, REL-8

#2001 Yellow: Enable PL011 console on J11 by default
  buildroot-external/board/raspberrypi/yellow/cmdline.txt
  buildroot-external/board/raspberrypi/yellow/config.txt
Labels: cla-signed, board/yellow, REL-8

#2008 Use yellow machine yellow_defconfig (landingpage)
  buildroot-external/configs/yellow_defconfig
Labels: cla-signed, board/yellow, REL-8

#1990 Better detail on the wifi setup
  Documentation/network.md
Labels: cla-signed

#2009 Use GitHub Container Registry for Supervisor (#2005)
  buildroot-external/package/hassio/dind-import-containers.sh
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed, os

#2010 Increase Supervisor start rate limit
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/hassos-supervisor.service
Labels: cla-signed, os

#2011 Improve HAOS builder Dockerfile
  .dockerignore
  Dockerfile
Labels: cla-signed, build

#2014 Fix ghcr URL
  buildroot-external/package/hassio/dind-import-containers.sh
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed

#2019 Linux: Update kernel 5.15.54
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64

#2018 Fix issue template link for developer documentation issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla-signed

#2012 Update README.md
  Documentation/boards/generic-x86-64/README.md
Labels: cla-signed

#2023 Allow to select generic-aarch64 and yellow in issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: cla-signed

#2025 Linux: Update kernel 5.15.55
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64

#2028 Linux: Update kernel 5.15.57
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, REL-8

#2034 Allow to Wipe essential boot files to trigger boot from USB host
  buildroot-external/board/raspberrypi/yellow/uboot-boot64.ush
Labels: cla-signed, board/yellow

#2035 Yellow USB mass storage support
  buildroot-external/board/raspberrypi/yellow/patches/linux/0001-ARM-dts-bcm2711-Add-device-tree-for-Home-Assistant-Y.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0002-ARM-dts-bcm2711-yellow-Mux-UART4-for-SiLabs-radio-mo.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0003-ARM-dts-bcm2711-yellow-Mux-debug-UART5.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0004-ARM-dts-bcm2711-yellow-Enable-I2C6-by-default.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0005-ARM-dts-bcm2711-yellow-add-I2S-audio-codec.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0006-ARM-dts-bcm2711-yellow-enable-GPIO-keys.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0007-ARM-dts-bcm2711-yellow-add-user-LED.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0008-ARM-dts-bcm2711-yellow-add-NXP-PCF85063A-RTC.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0009-ARM-dts-bcm2711-yellow-enable-USB-host-mode-by-defau.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0010-ARM-dts-bcm2711-yellow-use-generic-activity-trigger-.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0011-ARM-dts-bcm2711-yellow-use-USB-OTG-mode-by-default.patch
  buildroot-external/board/raspberrypi/yellow/uboot-boot64.ush
  buildroot-external/board/raspberrypi/yellow/uboot.config
Labels: cla-signed, board/yellow
