Repository home-assistant/operating-system, pull requests merged in 2022-04, with the labels that each got.

#1811 Enable wext backend for wpa_supplicant to support r8188eu
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/configs/yellow_defconfig
  buildroot-external/kernel/device-support.config
Labels: cla-signed

#1832 Enable IPv6 forwarding by default
  buildroot-external/rootfs-overlay/etc/sysctl.d/60-otbr-ip-forward.conf
Labels: cla-signed, os

#1836 Fix release drafter for release branches
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: cla-signed, build

#1842 Bump Home Assistant Yellow to Raspberry Pi Linux kernel 1.20220331
  Documentation/kernel.md
  buildroot-external/board/raspberrypi/yellow/patches/linux/0001-ARM-dts-bcm2711-Add-device-tree-for-Home-Assistant-Y.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0002-ARM-dts-bcm2711-yellow-Mux-UART4-for-SiLabs-radio-mo.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0003-ARM-dts-bcm2711-yellow-Mux-debug-UART5.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0004-ARM-dts-bcm2711-yellow-Enable-I2C6-by-default.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0005-ARM-dts-bcm2711-yellow-add-I2S-audio-codec.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0006-ARM-dts-bcm2711-yellow-enable-GPIO-keys.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0007-ARM-dts-bcm2711-yellow-add-user-LED.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0008-ARM-dts-bcm2711-yellow-add-NXP-PCF85063A-RTC.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0009-ARM-dts-bcm2711-yellow-enable-USB-host-mode-by-defau.patch
  buildroot-external/configs/yellow_defconfig
Labels: cla-signed, board/yellow

#1846 Cleanup Buildroot package for Raspberry Pi Bluetooth support
  buildroot-external/Config.in
  buildroot-external/busybox.config
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/yellow_defconfig
  buildroot-external/package/bluetooth-bcm43xx/0001-btuart-reduced-baud-rate-rpi3b.patch
  buildroot-external/package/bluetooth-bcm43xx/Config.in
  buildroot-external/package/bluetooth-bcm43xx/bluetooth-bcm43xx.mk
  buildroot-external/package/bluetooth-bcm43xx/bthelper@.service
  buildroot-external/package/pi-bluetooth/0001-Fix-Bluetooth-hci0-Frame-reassembly-failed-84.patch
  buildroot-external/package/pi-bluetooth/0002-Test-if-WiFi-Bluetooth-module-is-fitted-on-Compute-M.patch
  buildroot-external/package/pi-bluetooth/Config.in
  buildroot-external/package/pi-bluetooth/bthelper@.service
  buildroot-external/package/pi-bluetooth/hciuart.service
  buildroot-external/package/pi-bluetooth/pi-bluetooth.mk
Labels: cla-signed, board/raspberrypi

#1847 Yellow: Make UART5 the default UART in U-Boot
  buildroot-external/board/raspberrypi/yellow/patches/uboot/0001-drivers-bcm283x-don-t-explicitly-disable-init.patch
  buildroot-external/board/raspberrypi/yellow/patches/uboot/0002-drivers-bcm283x-allow-to-spawn-any-PL011-UART.patch
Labels: cla-signed, board/yellow

#1848 Add out-of-tree Gasket driver for Google Coral support (#1840, #1698)
  buildroot-external/Config.in
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/configs/yellow_defconfig
  buildroot-external/package/gasket/Config.in
  buildroot-external/package/gasket/gasket.mk
Labels: cla-signed, os

#1849 Linux: Update kernel 5.15.34
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas, board/generic-aarch64

#1851 Drop Coral drivers for 32-bit platforms
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed

#1857 Enable file system check for FAT boot partition
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/mnt-boot.mount
Labels: cla-signed, os

#1858 Add bugfix in GRUB2 squash4 squashfs code (#1830)
  buildroot-external/patches/grub2/0001-loadenv-add-file_env-to-load-var-from-file.patch
  buildroot-external/patches/grub2/0002-squash4-Fix-an-uninitialized-variable.patch
Labels: cla-signed, board/ova, board/generic-x86-64, board/generic-aarch64

#1856 Update configuration.md
  Documentation/configuration.md
Labels: cla-signed

#1863 Use board information from json for release builds
  .github/workflows/release.yml
Labels: cla-signed, build

#1864 Add USB storage quirks for Raspberry Pi by default (#1743)
  buildroot-external/board/raspberrypi/cmdline.txt
Labels: cla-signed, board/raspberrypi

#1865 Cleanup Yellow config.txt
  buildroot-external/board/raspberrypi/yellow/config.txt
Labels: cla-signed, board/yellow

#1866 Make container fetching more reliable
  buildroot-external/package/hassio/fetch-container-image.sh
Labels: cla-signed, build

#1867 Linux: Update kernel 5.15.35
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas, board/generic-aarch64

#1868 Support NVMe boot on Home Assistant Yellow
  buildroot-external/board/raspberrypi/yellow/patches/uboot/0001-drivers-bcm283x-don-t-explicitly-disable-init.patch
  buildroot-external/board/raspberrypi/yellow/patches/uboot/0002-drivers-bcm283x-allow-to-spawn-any-PL011-UART.patch
  buildroot-external/board/raspberrypi/yellow/patches/uboot/0003-nvme-improve-readability-of-nvme_setup_prps.patch
  buildroot-external/board/raspberrypi/yellow/patches/uboot/0004-nvme-Use-pointer-for-CPU-addressed-buffers.patch
  buildroot-external/board/raspberrypi/yellow/patches/uboot/0005-nvme-translate-virtual-addresses-into-the-bus-s-addr.patch
Labels: cla-signed, board/yellow

#1870 Add Network options required for OpenThread Border Router
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os, linux

#1873 Enable Intel Wireless WiFi DVM Firmware support (#1872)
  buildroot-external/board/pc/generic-x86-64/kernel.config
Labels: cla-signed, board/generic-x86-64

#1874 Handle long-press system keys only
  buildroot-external/rootfs-overlay/etc/systemd/logind.conf
Labels: cla-signed, os

#1875 Small Yellow improvements
  buildroot-external/board/raspberrypi/kernel.config
  buildroot-external/board/raspberrypi/yellow/patches/linux/0001-ARM-dts-bcm2711-Add-device-tree-for-Home-Assistant-Y.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0002-ARM-dts-bcm2711-yellow-Mux-UART4-for-SiLabs-radio-mo.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0003-ARM-dts-bcm2711-yellow-Mux-debug-UART5.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0004-ARM-dts-bcm2711-yellow-Enable-I2C6-by-default.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0005-ARM-dts-bcm2711-yellow-add-I2S-audio-codec.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0006-ARM-dts-bcm2711-yellow-enable-GPIO-keys.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0007-ARM-dts-bcm2711-yellow-add-user-LED.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0008-ARM-dts-bcm2711-yellow-add-NXP-PCF85063A-RTC.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0009-ARM-dts-bcm2711-yellow-enable-USB-host-mode-by-defau.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0010-ARM-dts-bcm2711-yellow-use-generic-activity-trigger-.patch
  buildroot-external/rootfs-overlay/etc/input-event-daemon.conf
Labels: cla-signed, board/yellow

#1876 Recreate defconfigs using savedefconfig target
  Makefile
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/configs/yellow_defconfig
Labels: cla-signed, build
