Repository home-assistant/operating-system, pull requests merged in 2022-03, with the labels that each got.

#1774 Update to latest Linux LTS kernel 5.15.25
  Documentation/kernel.md
  buildroot-external/Config.in
  buildroot-external/board/hardkernel/patches/linux/0001-arm64-dts-meson-add-i2c3-rtc-nodes-and-rtc-aliases-t.patch
  buildroot-external/board/hardkernel/patches/linux/0001-arm64-dts-meson-g12b-add-power-button-support.patch
  buildroot-external/board/hardkernel/patches/linux/0002-arm64-dts-meson-add-saradc-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0002-arm64-dts-meson-g12b-add-GPIO-fan-support.patch
  buildroot-external/board/hardkernel/patches/linux/0003-arm64-dts-meson-add-GPIO-line-names-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0003-arm64-dts-meson-g12b-odroid-n2-add-fan-as-cooling-de.patch
  buildroot-external/board/hardkernel/patches/linux/0004-arm64-dts-meson-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/0005-arm64-dts-meson-add-i2c2-node-to-ODROID-N2-N2.patch
  buildroot-external/board/hardkernel/patches/linux/0006-ODROID-C4-arm64-dts-add-uart_A-node.patch
  buildroot-external/board/hardkernel/patches/linux/0007-ODROID-C4-arm64-dts-add-i2c2-i2c3-node.patch
  buildroot-external/board/hardkernel/patches/linux/0009-Revert-of-fdt-Make-sure-no-map-does-not-remove-alrea.patch
  buildroot-external/board/hardkernel/patches/linux/0010-Revert-drm-meson_drv-add-shutdown-function.patch
  buildroot-external/board/hardkernel/patches/linux/hardkernel-0013-C4-arm64-dts-add-uart_A-node.patch
  buildroot-external/board/pc/generic-x86-64/kernel.config
  buildroot-external/board/pc/ova/kernel.config
  buildroot-external/board/pc/patches/linux/0001-iwlwifi-Make-missed-beacon-timeout-configurable.patch
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/configs/yellow_defconfig
  buildroot-external/package/intel-e1000e/Config.in
  buildroot-external/package/intel-e1000e/intel-e1000e.hash
  buildroot-external/package/intel-e1000e/intel-e1000e.mk
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64

#1776 Don't fail update even if files are missing
  buildroot-external/ota/rauc-hook
Labels: cla-signed, os-update

#1780 Add IP set support for iptables (#1778)
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os, linux

#1799 Revert "Remove git submodules before git checkout (#1611)"
  .github/workflows/dev.yml
  .github/workflows/release.yml
Labels: cla-signed, build

#1797 Use tempio to generate RAUC configuration files
  buildroot-external/Config.in
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/configs/yellow_defconfig
  buildroot-external/ota/manifest.raucm.gtpl
  buildroot-external/ota/system.conf.gtpl
  buildroot-external/package/tempio/Config.in.host
  buildroot-external/package/tempio/tempio.mk
  buildroot-external/scripts/ota.sh
  buildroot-external/scripts/rauc.sh
Labels: cla-signed, build, os-update

#1798 Add support for NTP configuration via DHCP (fixes #689)
  buildroot-external/rootfs-overlay/etc/systemd/timesyncd.conf
  buildroot-external/rootfs-overlay/usr/lib/NetworkManager/dispatcher.d/10-ntp
Labels: cla-signed

#1804 Add RTL_81XX firmware to raspberry pi devices
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
Labels: cla-signed

#1807 Use correct path for tempio
  buildroot-external/scripts/ota.sh
  buildroot-external/scripts/rauc.sh
Labels: cla-signed

#1794 Implement A/B switch when moving back to Barebox
  buildroot-external/board/pc/generic-x86-64/hassos-hook.sh
  buildroot-external/board/pc/ova/hassos-hook.sh
  buildroot-external/bootloader/barebox-state-efi-A.dtb
  buildroot-external/bootloader/barebox-state-efi-A.dts
  buildroot-external/bootloader/barebox-state-efi-B.dtb
  buildroot-external/bootloader/barebox-state-efi-B.dts
  buildroot-external/ota/rauc-hook
  buildroot-external/scripts/ota.sh
Labels: cla-signed, REL-7

#1813 Drop NetworkManager default config
  buildroot-external/rootfs-overlay/etc/NetworkManager/system-connections/default
  buildroot-external/rootfs-overlay/usr/libexec/hassos-overlay
  buildroot-external/scripts/rootfs-layer.sh
Labels: cla-signed, os

#1816 Linux: Update kernel 5.10.108
  Documentation/kernel.md
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas

#1817 Yellow: Bump Raspberry Pi kernel to 1.20220308
  buildroot-external/board/raspberrypi/yellow/patches/linux/0001-ARM-dts-bcm2711-Add-device-tree-for-Home-Assistant-Y.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0002-ARM-dts-bcm2711-yellow-Mux-UART4-for-SiLabs-radio-mo.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0003-ARM-dts-bcm2711-yellow-Mux-debug-UART5.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0004-ARM-dts-bcm2711-yellow-Enable-I2C6-by-default.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0005-ARM-dts-bcm2711-yellow-add-I2S-audio-codec.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0006-ARM-dts-bcm2711-yellow-enable-GPIO-keys.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0007-ARM-dts-bcm2711-yellow-add-user-LED.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0008-ARM-dts-bcm2711-yellow-add-NXP-PCF85063A-RTC.patch
  buildroot-external/board/raspberrypi/yellow/patches/linux/0009-ARM-dts-bcm2711-yellow-enable-USB-host-mode-by-defau.patch
  buildroot-external/configs/yellow_defconfig
Labels: cla-signed, board/yellow

#1818 Linux: Update kernel 5.15.32
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
  scripts/update-kernel-upstream.sh
Labels: cla-signed, board/ova, board/odroid, board/tinker, board/generic-x86-64, board/khadas, board/generic-aarch64

#1823 Set GRUB2 bootloader timeout to 1s
  buildroot-external/board/arm-uefi/generic-aarch64/grub.cfg
  buildroot-external/board/pc/grub.cfg
Labels: cla-signed, os

#1824 Enable nftables packet filtering as modules (#1812)
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os

#1825 Use anonymous Docker volume as build output
  .github/workflows/dev.yml
  scripts/entry.sh
Labels: cla-signed, build
