Repository home-assistant/operating-system, pull requests merged in 2023-03, with the labels that each got.

#2375 Increase net.core.optmem_max for OTBR
  buildroot-external/rootfs-overlay/etc/sysctl.d/60-otbr-ancillary-buffer.conf
Labels: cla-signed, os

#2379 Enable NetworkManager command line utility nmcli explicitly
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/configs/yellow_defconfig
Labels: cla-signed, os

#2380 Use Network device naming scheme v250
  buildroot-external/board/arm-uefi/generic-aarch64/grub.cfg
  buildroot-external/board/asus/tinker/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-n2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
  buildroot-external/board/khadas/vim3/uboot-boot.ush
  buildroot-external/board/pc/grub.cfg
  buildroot-external/board/raspberrypi/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot64.ush
  buildroot-external/board/raspberrypi/yellow/uboot-boot64.ush
Labels: cla-signed, os

#2381 Enable Microsoft HyperV integration services
  buildroot-external/configs/ova_defconfig
Labels: cla-signed, board/ova, hypervisor/hyper-v

#2382 Use new containerd.sock location of Docker 23.0
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: os

#2383 Linux: Update kernel 6.1.15
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64

#2385 Support custom sized SPL/raw boot region
  buildroot-external/board/arm-uefi/generic-aarch64/meta
  buildroot-external/board/asus/tinker/meta
  buildroot-external/board/hardkernel/odroid-c2/meta
  buildroot-external/board/hardkernel/odroid-c4/meta
  buildroot-external/board/hardkernel/odroid-n2/meta
  buildroot-external/board/hardkernel/odroid-xu4/meta
  buildroot-external/board/khadas/vim3/meta
  buildroot-external/board/pc/generic-x86-64/meta
  buildroot-external/board/pc/ova/meta
  buildroot-external/board/raspberrypi/rpi2/meta
  buildroot-external/board/raspberrypi/rpi3-64/meta
  buildroot-external/board/raspberrypi/rpi3/meta
  buildroot-external/board/raspberrypi/rpi4-64/meta
  buildroot-external/board/raspberrypi/rpi4/meta
  buildroot-external/board/raspberrypi/yellow/meta
  buildroot-external/scripts/hdd-image.sh
Labels: cla-signed, build

#2386 Avoid custom GPT location
  buildroot-external/ota/rauc-hook
  buildroot-external/scripts/hdd-image.sh
Labels: cla-signed, build, board/tinker

#2388 Add label action for new features
  .github/label-actions.yml
Labels: cla-signed, build

#2389 Add libseccomp
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/configs/yellow_defconfig
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os

#2391 Bump QEMU guest agent to 7.2.0
  buildroot-external/package/qemu-guest-agent/qemu-guest-agent.hash
  buildroot-external/package/qemu-guest-agent/qemu-guest-agent.mk
Labels: cla-signed, board/ova

#2396 Linux: Update kernel 6.1.16
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64

#2387 Add ODROID-M1 support
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/matrix.json
  Documentation/kernel.md
  buildroot-external/Config.in
  buildroot-external/board/hardkernel/kernel-rockchip.config
  buildroot-external/board/hardkernel/odroid-m1/boot-env.txt
  buildroot-external/board/hardkernel/odroid-m1/cmdline.txt
  buildroot-external/board/hardkernel/odroid-m1/hassos-hook.sh
  buildroot-external/board/hardkernel/odroid-m1/kernel.config
  buildroot-external/board/hardkernel/odroid-m1/meta
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0001-arm64-dts-rockchip-Add-Hardkernel-ODROID-M1-board.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0002-arm64-dts-rockchip-add-thermal-support-to-ODROID-M1.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0003-arm64-dts-rockchip-Add-NOR-flash-to-ODROID-M1.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0004-arm64-dts-rockchip-Add-analog-audio-on-ODROID-M1.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0005-arm64-dts-rockchip-Enable-vop2-and-hdmi-tx-on-ODROID.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0006-arm64-dts-rockchip-Enable-HDMI-audio-on-ODROID-M1.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0007-arm64-dts-rockchip-Enable-the-GPU-on-ODROID-M1.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0008-arm64-dts-rockchip-Enable-the-USB-2.0-ports-on-ODROI.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0009-arm64-dts-rockchip-Enable-the-USB-3.0-ports-on-ODROI.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0010-arm64-dts-rockchip-Add-SATA-support-to-ODROID-M1.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0011-arm64-dts-rockchip-Add-PCIEe-v3-nodes-to-ODROID-M1.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/linux/0012-arm64-dts-rockchip-Add-IR-receiver-node-to-ODROID-M1.patch
  buildroot-external/board/hardkernel/odroid-m1/patches/uboot/0001-arm64-dts-rockchip-rk3568-Add-ODROID-M1-board-suppor.patch
  buildroot-external/board/hardkernel/odroid-m1/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-m1/uboot.config
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/package/rockchip-blobs/Config.in
  buildroot-external/package/rockchip-blobs/rockchip-blobs.mk
  buildroot-external/scripts/hdd-image.sh
Labels: cla-signed

#2400 Add Multi-Gen LRU (disabled by default)
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os

#2401 Linux: Update kernel 6.1.18
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64

#2402 Add ODROID-M1 to documentation
  Documentation/boards/README.md
  Documentation/boards/hardkernel/README.md
  Documentation/boards/hardkernel/odroid-c2.md
  Documentation/boards/hardkernel/odroid-c4.md
  Documentation/boards/hardkernel/odroid-m1.md
  Documentation/boards/hardkernel/odroid-n2.md
  Documentation/kernel.md
  scripts/update-kernel-upstream.sh
Labels: cla-signed, Documentation, board/odroid

#2403 Fix U-Boot environment size for ODROID-M1
  buildroot-external/board/hardkernel/odroid-m1/meta
Labels: cla-signed, board/odroid, u-boot

#2406 Capitalize ODROID as used by Hardkernel
  buildroot-external/board/hardkernel/odroid-c2/meta
  buildroot-external/board/hardkernel/odroid-c4/meta
  buildroot-external/board/hardkernel/odroid-n2/meta
  buildroot-external/board/hardkernel/odroid-xu4/meta
  buildroot-external/package/hardkernel-boot/Config.in
  buildroot-external/package/rpi-rf-mod/Config.in
  buildroot-external/package/rpi-rf-mod/rpi-rf-mod.mk
Labels: cla-signed, board/odroid, build

#2407 Choose Security Module using Kernel configuration
  buildroot-external/board/arm-uefi/generic-aarch64/grub.cfg
  buildroot-external/board/asus/tinker/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-m1/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-n2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
  buildroot-external/board/khadas/vim3/uboot-boot.ush
  buildroot-external/board/pc/grub.cfg
  buildroot-external/board/raspberrypi/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot64.ush
  buildroot-external/board/raspberrypi/yellow/uboot-boot64.ush
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os, linux

#2409 Support systemd ConditionFirstBoot
  buildroot-external/board/arm-uefi/generic-aarch64/grub.cfg
  buildroot-external/board/asus/tinker/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-m1/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-n2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
  buildroot-external/board/khadas/vim3/uboot-boot.ush
  buildroot-external/board/pc/grub.cfg
  buildroot-external/board/raspberrypi/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot64.ush
  buildroot-external/board/raspberrypi/yellow/uboot-boot64.ush
Labels: cla-signed, os, u-boot, grub2

#2410 Deactivate any external data disk device on first boot (#2390)
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/haos-data-disk-detach.service
  buildroot-external/rootfs-overlay/usr/libexec/haos-data-disk-detach
Labels: cla-signed, os

#2411 Linux: Update kernel 6.1.19
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64

#2412 Avoid moving data to same device
  buildroot-external/rootfs-overlay/usr/libexec/hassos-data
Labels: cla-signed, os

#2416 Bump HAOS Agent to 1.5.1
  buildroot-external/package/os-agent/os-agent.mk
Labels: cla-signed, os

#2417 Linux: Update kernel to 6.1.19 for Raspberry Pi systems
  Documentation/kernel.md
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/yellow_defconfig
Labels: cla-signed, board/raspberrypi, linux, board/yellow

#2418 Linux: Update kernel 6.1.20
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64

#2419 Bump U-Boot for ODROID-M1 to 2023.04-rc4
  buildroot-external/configs/odroid_m1_defconfig
Labels: cla-signed, board/odroid, u-boot

#2423 Linux: Update kernel 6.1.21
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64

#2424 Don't kill ssh connection on OOM
  buildroot-external/rootfs-overlay/etc/systemd/system/dropbear.service.d/hassos.conf
Labels: cla-signed, os

#2425 Partially revert "improve virtual hw support (#2138)"
  buildroot-external/board/pc/ova/kernel.config
Labels: cla-signed, board/ova

#2427 Fix swapfile creation for all memory sizes
  buildroot-external/rootfs-overlay/usr/libexec/haos-swapfile
Labels: cla-signed, os, rel-10

#2431 updated generic_raw_uart and rpi-rf-mod to latest versions.
  buildroot-external/package/generic_raw_uart/generic_raw_uart.hash
  buildroot-external/package/generic_raw_uart/generic_raw_uart.mk
  buildroot-external/package/rpi-rf-mod/rpi-rf-mod.hash
  buildroot-external/package/rpi-rf-mod/rpi-rf-mod.mk
Labels: cla-signed, rel-10

#2434 Improve IPv6 NDP for non-local Thread Border routers
  buildroot-external/kernel/hassos.config
  buildroot-external/patches/linux/0001-ipv6-add-option-to-explicitly-enable-reachability-te.patch
  buildroot-external/patches/network-manager/0001-ndisc-support-multiple-gateways-for-a-single-network.patch
Labels: cla-signed, os, rel-10

#2436 Set umask on swapfile creation
  buildroot-external/rootfs-overlay/usr/libexec/haos-swapfile
Labels: cla-signed, os, rel-10

#2441 Linux: Update kernel 6.1.22
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64

#2443 Use zsmalloc for zswap
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os

#2392 Enable Multi-Gen LRU
  buildroot-external/kernel/hassos.config
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/haos-mglru.service
Labels: cla-signed, os
