Repository home-assistant/operating-system, pull requests merged in 2023-09, with the labels that each got.

#2719 Remove checkout twice in dev build workflow
  .github/workflows/dev.yml
Labels: cla-signed

#2721 Use full preemptible kernel in Home Assistant OS
  buildroot-external/kernel/hassos.config
Labels: cla-signed, os

#2726 Linux: Update kernel 6.1.51
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, rel-10

#2730 Improve LED representation in Home Assistant Green device tree
  buildroot-external/board/nabucasa/green/patches/linux/0007-arch-arm64-dts-green-Improve-LED-representation.patch
Labels: cla-signed, os

#2731 Separate build step when loading container images
  buildroot-external/package/hassio/hassio.mk
Labels: cla-signed, build

#2732 Improve GitHub Action caching
  .github/workflows/dev.yml
Labels: cla-signed, build

#2734 Bump HAOS Agent to 1.6.0
  buildroot-external/package/os-agent/os-agent.mk
Labels: cla-signed, os

#2736 Enable ECC memory support via EDAC (#2708)
  buildroot-external/board/pc/generic-x86-64/kernel.config
Labels: cla-signed, board/generic-x86-64

#2739 Execute stale workflow only once a day
  .github/workflows/stale.yml
Labels: cla-signed, build

#2740 Linux: Update kernel 6.1.52
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, rel-10

#2743 Combine downloads and compile cache in GitHub Action cache
  .github/workflows/dev.yml
Labels: cla-signed, build

#2745 Don't combine GitHub action caches
  .github/workflows/dev.yml
Labels: cla-signed, build

#2750 Linux: Update kernel 6.1.53
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, rel-10

#2751 Delete Bluetooth device cache regularly
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/haos-bt-cache.service
  buildroot-external/rootfs-overlay/usr/lib/systemd/system/haos-bt-cache.timer
Labels: cla-signed, os, bluetooth

#2760 Linux: Update kernel 6.1.54
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, rel-10

#2764 Unify release and dev GitHub actions
  .github/workflows/build.yaml
  .github/workflows/release.yml
Labels: cla-signed, build

#2765 Download latest stable Supervisor after device wipe
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed, os

#2767 Adjust Home Assistant OS versioning to prepare for new release strategy
  .github/workflows/build.yaml
  Makefile
  buildroot-external/meta
  buildroot-external/scripts/name.sh
Labels: cla-signed, os, build

#2769 Linux: Update kernel 6.1.55
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, rel-10

#2773 Disable overlayfs features not used by Docker
  buildroot-external/kernel/docker.config
Labels: cla-signed, os

#2772 generic-x86-64: enable backlight support
  buildroot-external/board/pc/generic-x86-64/kernel.config
Labels: cla-signed, board/generic-x86-64
