Repository home-assistant/operating-system, pull requests merged in 2024-07, with the labels that each got.

#3451 Fix rauc hook to restore machine-id in new grub environment
  buildroot-external/ota/rauc-hook
Labels: cla-signed

#3457 Remove old code from rauc-hook and GRUB env initialization
  buildroot-external/board/pc/generic-x86-64/hassos-hook.sh
  buildroot-external/board/pc/ova/hassos-hook.sh
  buildroot-external/ota/rauc-hook
Labels: cla-signed, os

#3458 Populate grubenv with RAUC data in clean aarch64 OS image
  buildroot-external/board/arm-uefi/generic-aarch64/hassos-hook.sh
Labels: cla-signed, board/generic-aarch64

#3463 Linux: Update kernel to 6.6.37
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_m1s_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, board/green

#3464 Refer to GRUB instead of Barebox in top-level readme
  README.md
Labels: cla-signed, Documentation

#3467 Enable aQuantia AQtion ethernet driver
  buildroot-external/kernel/v6.6.y/device-support-pci.config
Labels: cla-signed, board/ova, board/generic-x86-64

#3468 Enable i6300ESB watchdog driver for generic-aarch64
  buildroot-external/board/arm-uefi/generic-aarch64/kernel.config
Labels: cla-signed, linux, board/generic-aarch64

#3470 Revert "Revert GRUB2 patch causing boot failure on some old x86_64 BIOSes (#3324)"
  buildroot-external/board/pc/generic-x86-64/patches/grub2/0001-Revert-efi-Use-generic-EFI-loader-for-x86_64-and-i38.patch
  buildroot-external/configs/generic_x86_64_defconfig
Labels: cla-signed, board/generic-x86-64, grub2

#3482 Linux: Update kernel to 6.6.41
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_m1s_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, board/green

#3456 Use EROFS for the root filesystem
  .github/workflows/build.yaml
  buildroot-external/board/asus/tinker/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-c4/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-m1/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-m1s/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-n2/uboot-boot.ush
  buildroot-external/board/hardkernel/odroid-xu4/uboot-boot.ush
  buildroot-external/board/khadas/vim3/uboot-boot.ush
  buildroot-external/board/nabucasa/green/uboot-boot.ush
  buildroot-external/board/raspberrypi/rpi5-64/cmdline.txt
  buildroot-external/board/raspberrypi/uboot-boot.ush
  buildroot-external/board/raspberrypi/uboot-boot64.ush
  buildroot-external/board/raspberrypi/yellow/uboot-boot64.ush
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_m1s_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/rpi2_defconfig
  buildroot-external/configs/rpi3_64_defconfig
  buildroot-external/configs/rpi3_defconfig
  buildroot-external/configs/rpi4_64_defconfig
  buildroot-external/configs/rpi4_defconfig
  buildroot-external/configs/rpi5_64_defconfig
  buildroot-external/configs/tinker_defconfig
  buildroot-external/configs/yellow_defconfig
  buildroot-external/genimage/image-raucb-nospl.cfg
  buildroot-external/genimage/image-raucb-spl.cfg
  buildroot-external/genimage/partitions-os-gpt.cfg
  buildroot-external/genimage/partitions-os-mbr.cfg
  buildroot-external/kernel/v6.6.y/hassos.config
  buildroot-external/scripts/hdd-image.sh
  buildroot-external/scripts/name.sh
Labels: cla-signed, os

#3491 Reduce log spam from Docker health checks
  buildroot-external/rootfs-overlay/etc/systemd/system/run-docker-.mount.d/10-reduce-verbosity.conf
Labels: cla-signed

#3492 Enable Netfilter MARK match kernel configuration
  buildroot-external/kernel/v6.6.y/hassos.config
Labels: cla-signed, os

#3493 Allow EROFS compression for Rockchip kernels
  buildroot-external/kernel/v6.6.y/kernel-arm64-rockchip.config
Labels: cla-signed, board/odroid, board/green

#3495 Linux: Update kernel to 6.6.43
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_m1s_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, board/green

#3497 Patch genimage to force first usable LBA @ 34 to fix RPi 5/Windows issues
  buildroot-external/patches/genimage/0002-image-hd-do-not-use-first-partition-offset-for-GPT-s.patch
Labels: cla-signed, board/raspberrypi, build
