Repository home-assistant/operating-system, pull requests merged in 2025-09, with the labels that each got.

#4267 Fix broken outgoing connections caused by upstream kernel regression
  buildroot-external/patches/linux/6.12.43/0001-ipv6-add-option-to-explicitly-enable-reachability-te.patch
  buildroot-external/patches/linux/6.12.43/0002-net-ipv4-fix-regression-in-local-broadcast-routes.patch
Labels: cla-signed, linux

#4279 Enable Pressure Stall Information PSI
  buildroot-external/kernel/v6.12.y/hassos.config
Labels: cla-signed

#4276 Start Supervisor container with its cidfile mounted to /run/cid
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed, os

#4281 Support Chelsio T4/T5/T6 VF in SRIOV mode
  buildroot-external/board/pc/ova/kernel.config
Labels: cla-signed
