Repository home-assistant/operating-system, pull requests merged in 2025-07, with the labels that each got.

#4132 Do not disable RPi Bluetooth if Wi-Fi is not present
  buildroot-external/package/pi-bluetooth/hcidisable.service
  buildroot-external/package/pi-bluetooth/pi-bluetooth.mk
Labels: cla-signed, board/raspberrypi, board/yellow, bluetooth

#4133 Mount Systemd Journal socket to the Supervisor container
  buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
Labels: cla-signed, os

#4137 Make all Raspberry Pi LAN drivers built-in
  buildroot-external/board/raspberrypi/kernel.config
Labels: cla-signed, board/raspberrypi, board/yellow

#4138 Fix Hailo v4.21.0 driver traces due to missing lock
  buildroot-external/package/hailo-pci/0001-Add-missing-lock-around-current-mm.patch
Labels: cla-signed, board/raspberrypi

#4173 Drop experimental and ip6tables config
  buildroot-external/rootfs-overlay/etc/docker/daemon.json
Labels: cla-signed

#4187 Generate Virtual Disk Image (VDI) for aarch64 build
  buildroot-external/board/arm-uefi/generic-aarch64/hassos-hook.sh
Labels: cla-signed, board/generic-aarch64

#4192 Enable driver for Xilinx AMS adc sensor
  buildroot-external/board/arm-uefi/generic-aarch64/kernel.config
Labels: cla-signed

#4196 Linux: Update kernel to 6.12.40
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_m1s_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, board/green

#4197 Fix systemd-journal-gatewayd 100% CPU issue when watching logs
  buildroot-external/patches/systemd/0007-journal-gatewayd-fix-busy-loop-when-following-way-be.patch
Labels: cla-signed, os
