Repository home-assistant/operating-system, pull requests merged in 2025-06, with the labels that each got.

#4095 Bump Hailo driver and firmware to v4.21.0
  buildroot-external/package/hailo-pci/hailo-pci.hash
  buildroot-external/package/hailo-pci/hailo-pci.mk
  buildroot-external/package/hailo8-firmware/hailo8-firmware.hash
  buildroot-external/package/hailo8-firmware/hailo8-firmware.mk
Labels: cla-signed, board/raspberrypi, board/ova, board/generic-x86-64, board/yellow, board/generic-aarch64

#4091 Add Intel Cannon Lake pinctrl driver
  buildroot-external/board/pc/generic-x86-64/kernel.config
Labels: cla-signed, board/generic-x86-64

#4105 Add Marvell 88E1XXX driver for x86-64
  buildroot-external/board/pc/generic-x86-64/kernel.config
Labels: cla-signed, linux, board/generic-x86-64

#4108 Add tests for OS update and boot slot switching
  tests/smoke_test/test_os_update.py
Labels: cla-signed, build

#4113 Fix flaky timeout after boot slot switching test
  tests/smoke_test/test_os_update.py
Labels: cla-signed, build

#4115 Enable Intel IXGBE driver, clean up Intel NIC config options
  buildroot-external/board/hardkernel/kernel-amlogic.config
  buildroot-external/board/khadas/kernel-vim.config
  buildroot-external/kernel/v6.12.y/device-support-pci.config
  buildroot-external/kernel/v6.12.y/kernel-arm64-rockchip.config
Labels: cla-signed, linux

#4130 Linux: Update kernel to 6.12.35
  Documentation/kernel.md
  buildroot-external/configs/generic_aarch64_defconfig
  buildroot-external/configs/generic_x86_64_defconfig
  buildroot-external/configs/green_defconfig
  buildroot-external/configs/khadas_vim3_defconfig
  buildroot-external/configs/odroid_c2_defconfig
  buildroot-external/configs/odroid_c4_defconfig
  buildroot-external/configs/odroid_m1_defconfig
  buildroot-external/configs/odroid_m1s_defconfig
  buildroot-external/configs/odroid_n2_defconfig
  buildroot-external/configs/odroid_xu4_defconfig
  buildroot-external/configs/ova_defconfig
  buildroot-external/configs/tinker_defconfig
Labels: cla-signed, board/ova, board/odroid, board/tinker, linux, board/generic-x86-64, board/khadas, board/generic-aarch64, board/green
